# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel


class AgenticTransitionOptionParamsValue_Input(UniversalBaseModel):
    type: typing.Literal["input"] = "input"
    name: str

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class AgenticTransitionOptionParamsValue_Literal(UniversalBaseModel):
    type: typing.Literal["literal"] = "literal"
    value: typing.Any

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class AgenticTransitionOptionParamsValue_Output(UniversalBaseModel):
    type: typing.Literal["output"] = "output"
    stage: str
    name: str

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


AgenticTransitionOptionParamsValue = typing_extensions.Annotated[
    typing.Union[
        AgenticTransitionOptionParamsValue_Input,
        AgenticTransitionOptionParamsValue_Literal,
        AgenticTransitionOptionParamsValue_Output,
    ],
    pydantic.Field(discriminator="type"),
]
