# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata
from .agentic_transition_option import AgenticTransitionOption
from .agentic_transition_output_instructions import AgenticTransitionOutputInstructions


class AgenticTransitionOutput(UniversalBaseModel):
    id: str
    from_: typing_extensions.Annotated[str, FieldMetadata(alias="from"), pydantic.Field(alias="from")]
    instructions: AgenticTransitionOutputInstructions
    options: typing.Optional[typing.List[AgenticTransitionOption]] = None
    label: typing.Optional[str] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
