# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from .auth_verifier_six_type import AuthVerifierSixType
from .ip_allowlist_verifier import IpAllowlistVerifier


class AuthVerifierSix(IpAllowlistVerifier):
    type: AuthVerifierSixType

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
