# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .byo_connection_state import ByoConnectionState
from .byo_source_kind import ByoSourceKind


class ByoProviderStatus(UniversalBaseModel):
    message: typing.Optional[str] = None
    provider_name: typing.Optional[str] = None
    source_kind: ByoSourceKind
    state: ByoConnectionState

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
