# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel


class CaPublicKeyResponse(UniversalBaseModel):
    """
    Response containing the CA public key for trusting certificates.
    """

    public_key: str = pydantic.Field()
    """
    CA public key in OpenSSH format (for TrustedUserCAKeys)
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
