# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel, update_forward_refs


class CompoundConditionInput(UniversalBaseModel):
    conditions: typing.List["LineConditionInput"]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


from .line_condition_input import LineConditionInput  # noqa: E402, I001
from .not_condition_input import NotConditionInput  # noqa: E402, I001

update_forward_refs(CompoundConditionInput, LineConditionInput=LineConditionInput, NotConditionInput=NotConditionInput)
