# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .custom_service import CustomService


class CustomServicesResponse(UniversalBaseModel):
    """
    List of custom services defined in the current tenant.
    """

    services: typing.List[CustomService]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
