# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .auth_method import AuthMethod


class CustomIntegration(UniversalBaseModel):
    """
    Tenant-scoped custom integration spec.

    The frontend owns slug derivation (live preview matches what's stored).
    The backend treats ``slug`` as authoritative input and only validates its
    shape -- it never re-derives. ``name`` is the free-form human label and
    is allowed to contain anything reasonable.
    """

    auth_method: typing.Optional[AuthMethod] = None
    authorization_url: typing.Optional[str] = None
    client_id: typing.Optional[str] = None
    client_secret: typing.Optional[str] = None
    mcp_url: typing.Optional[str] = None
    name: str
    scopes: typing.Optional[typing.List[str]] = None
    slug: str
    token_url: typing.Optional[str] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
