# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .environment_entry_response import EnvironmentEntryResponse


class EnvironmentResponse(UniversalBaseModel):
    created_at: dt.datetime
    entries: typing.List[EnvironmentEntryResponse]
    id: str
    is_default: bool
    name: str
    updated_at: dt.datetime

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
