# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel


class ExecResponse(UniversalBaseModel):
    """
    Command execution started response.
    """

    exec_id: str
    sandbox_id: str
    status: str

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
