# This file was auto-generated by Fern from our API Definition.

import typing

from ..core import enum

T_Result = typing.TypeVar("T_Result")


class FactoryFailureDomain(enum.StrEnum):
    """
    Who owns the fix for a failed line run.
    """

    PLATFORM = "platform"
    CONFIG = "config"
    CONTRACT = "contract"
    INFRA = "infra"
    AGENT = "agent"
    USER = "user"
    UNKNOWN = "unknown"
    _UNKNOWN = "__FACTORYFAILUREDOMAIN_UNKNOWN__"
    """
    This member is used for forward compatibility. If the value is not recognized by the enum, it will be stored here, and the raw value is accessible through `.value`.
    """

    @classmethod
    def _missing_(cls, value: typing.Any) -> "FactoryFailureDomain":
        unknown = cls._UNKNOWN
        unknown._value_ = value
        return unknown

    def visit(
        self,
        platform: typing.Callable[[], T_Result],
        config: typing.Callable[[], T_Result],
        contract: typing.Callable[[], T_Result],
        infra: typing.Callable[[], T_Result],
        agent: typing.Callable[[], T_Result],
        user: typing.Callable[[], T_Result],
        unknown: typing.Callable[[], T_Result],
        _unknown_member: typing.Callable[[str], T_Result],
    ) -> T_Result:
        if self is FactoryFailureDomain.PLATFORM:
            return platform()
        if self is FactoryFailureDomain.CONFIG:
            return config()
        if self is FactoryFailureDomain.CONTRACT:
            return contract()
        if self is FactoryFailureDomain.INFRA:
            return infra()
        if self is FactoryFailureDomain.AGENT:
            return agent()
        if self is FactoryFailureDomain.USER:
            return user()
        if self is FactoryFailureDomain.UNKNOWN:
            return unknown()
        return _unknown_member(self._value_)
