# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .factory_status import FactoryStatus


class FactoryResponse(UniversalBaseModel):
    id: str
    key: str
    name: str
    color: str
    icon: str
    status: FactoryStatus
    is_default: bool
    created_at: dt.datetime
    updated_at: dt.datetime

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
