# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .factory_metrics_response import FactoryMetricsResponse
from .factory_overview_item import FactoryOverviewItem


class FactoryOverview(UniversalBaseModel):
    total: int
    draft: int
    active: int
    cancelled: int
    metrics: FactoryMetricsResponse
    factories: typing.Optional[typing.List[FactoryOverviewItem]] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
