# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel


class GitHubExternalRef(UniversalBaseModel):
    """
    GitHub identity: PRs/issues use owner, repo, and number; comments use id.
    """

    kind: str
    owner: typing.Optional[str] = None
    repo: typing.Optional[str] = None
    number: typing.Optional[int] = None
    node_id: typing.Optional[str] = None
    id: typing.Optional[str] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
