# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .incoming_webhook_secret import IncomingWebhookSecret


class HeaderEqualsVerifier(UniversalBaseModel):
    header: str
    value: IncomingWebhookSecret

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
