# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .auth_verifier import AuthVerifier
from .incoming_webhook_auth_one_auth_type import IncomingWebhookAuthOneAuthType


class IncomingWebhookAuthOne(UniversalBaseModel):
    auth_type: IncomingWebhookAuthOneAuthType
    verifiers: typing.List[AuthVerifier]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
