# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .incoming_webhook_action import IncomingWebhookAction
from .incoming_webhook_condition import IncomingWebhookCondition


class IncomingWebhookRule(UniversalBaseModel):
    actions: typing.List[IncomingWebhookAction]
    when: typing.Optional[IncomingWebhookCondition] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
