# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from .incoming_webhook_auto_resume_policy import IncomingWebhookAutoResumePolicy
from .incoming_webhook_sandbox_template import IncomingWebhookSandboxTemplate
from .payload_mapping import PayloadMapping


class IncomingWebhookAction_EnsureSandbox(UniversalBaseModel):
    action_type: typing.Literal["ensure_sandbox"] = "ensure_sandbox"
    template: IncomingWebhookSandboxTemplate

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class IncomingWebhookAction_ResumeSandbox(UniversalBaseModel):
    action_type: typing.Literal["resume_sandbox"] = "resume_sandbox"

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class IncomingWebhookAction_PauseSandbox(UniversalBaseModel):
    action_type: typing.Literal["pause_sandbox"] = "pause_sandbox"

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class IncomingWebhookAction_DeleteSandbox(UniversalBaseModel):
    action_type: typing.Literal["delete_sandbox"] = "delete_sandbox"

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class IncomingWebhookAction_DeliverToPort(UniversalBaseModel):
    action_type: typing.Literal["deliver_to_port"] = "deliver_to_port"
    auto_resume: typing.Optional[IncomingWebhookAutoResumePolicy] = None
    path: typing.Optional[str] = None
    payload: typing.Optional[PayloadMapping] = None
    port: int

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


IncomingWebhookAction = typing_extensions.Annotated[
    typing.Union[
        IncomingWebhookAction_EnsureSandbox,
        IncomingWebhookAction_ResumeSandbox,
        IncomingWebhookAction_PauseSandbox,
        IncomingWebhookAction_DeleteSandbox,
        IncomingWebhookAction_DeliverToPort,
    ],
    pydantic.Field(discriminator="action_type"),
]
