# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .hmac_algorithm import HmacAlgorithm
from .incoming_webhook_secret_ref import IncomingWebhookSecretRef
from .signature_encoding import SignatureEncoding
from .signed_payload import SignedPayload
from .value_source import ValueSource


class IncomingWebhookAuthResponseHmac(UniversalBaseModel):
    algorithm: HmacAlgorithm
    encoding: SignatureEncoding
    prefix: typing.Optional[str] = None
    secret_redacted: bool
    secret_ref: IncomingWebhookSecretRef
    signature: ValueSource
    signed_payload: SignedPayload

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
