# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .job_param_mapping import JobParamMapping


class IncomingWebhookActionTriggerJob(UniversalBaseModel):
    job_name: str
    params: typing.Optional[typing.Dict[str, typing.Optional[JobParamMapping]]] = None
    region: typing.Optional[str] = None
    version_id: typing.Optional[str] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
