# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .value_source import ValueSource


class IncomingWebhookTargetSandboxNameFromEvent(UniversalBaseModel):
    allowed_names: typing.Optional[typing.List[str]] = None
    allowed_pattern: typing.Optional[str] = None
    required_prefix: typing.Optional[str] = None
    source: ValueSource

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
