# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .incoming_webhook_git_source import IncomingWebhookGitSource
from .incoming_webhook_sandbox_lifecycle import IncomingWebhookSandboxLifecycle
from .incoming_webhook_setup_script import IncomingWebhookSetupScript
from .legacy_init_capability import LegacyInitCapability
from .sandbox_init import SandboxInit


class IncomingWebhookSandboxTemplate(UniversalBaseModel):
    cache_key: typing.Optional[str] = None
    disk_gb: int
    env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None
    gateway_profile: typing.Optional[str] = None
    image: str
    init: typing.Optional[SandboxInit] = None
    init_capabilities: typing.Optional[typing.List[LegacyInitCapability]] = None
    lifecycle: typing.Optional[IncomingWebhookSandboxLifecycle] = None
    memory_mb: int
    setup_scripts: typing.Optional[typing.List[IncomingWebhookSetupScript]] = None
    snapshot_name: typing.Optional[str] = None
    snapshot_url: typing.Optional[str] = None
    sources: typing.Optional[typing.List[IncomingWebhookGitSource]] = None
    vcpus: int
    workdir: typing.Optional[str] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
