# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .incoming_webhook_auth_zero_auth_type import IncomingWebhookAuthZeroAuthType


class IncomingWebhookAuthZero(UniversalBaseModel):
    auth_type: IncomingWebhookAuthZeroAuthType

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
