# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from .auth_verifier_response import AuthVerifierResponse
from .hmac_algorithm import HmacAlgorithm
from .incoming_webhook_secret_ref import IncomingWebhookSecretRef
from .signature_encoding import SignatureEncoding
from .signed_payload import SignedPayload
from .value_source import ValueSource


class IncomingWebhookAuthResponse_None(UniversalBaseModel):
    auth_type: typing.Literal["none"] = "none"

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class IncomingWebhookAuthResponse_All(UniversalBaseModel):
    auth_type: typing.Literal["all"] = "all"
    verifiers: typing.List[AuthVerifierResponse]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class IncomingWebhookAuthResponse_Any(UniversalBaseModel):
    auth_type: typing.Literal["any"] = "any"
    verifiers: typing.List[AuthVerifierResponse]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class IncomingWebhookAuthResponse_Hmac(UniversalBaseModel):
    auth_type: typing.Literal["hmac"] = "hmac"
    algorithm: HmacAlgorithm
    encoding: SignatureEncoding
    prefix: typing.Optional[str] = None
    secret_redacted: bool
    secret_ref: IncomingWebhookSecretRef
    signature: ValueSource
    signed_payload: SignedPayload

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class IncomingWebhookAuthResponse_HeaderEquals(UniversalBaseModel):
    auth_type: typing.Literal["header_equals"] = "header_equals"
    header: str
    value_redacted: bool

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class IncomingWebhookAuthResponse_QueryEquals(UniversalBaseModel):
    auth_type: typing.Literal["query_equals"] = "query_equals"
    query: str
    value_redacted: bool

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class IncomingWebhookAuthResponse_Basic(UniversalBaseModel):
    auth_type: typing.Literal["basic"] = "basic"
    secret_redacted: bool

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class IncomingWebhookAuthResponse_BearerStatic(UniversalBaseModel):
    auth_type: typing.Literal["bearer_static"] = "bearer_static"
    secret_redacted: bool

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class IncomingWebhookAuthResponse_Jwt(UniversalBaseModel):
    auth_type: typing.Literal["jwt"] = "jwt"
    audience: typing.Optional[str] = None
    issuer: typing.Optional[str] = None
    jwks_url: str

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class IncomingWebhookAuthResponse_IpAllowlist(UniversalBaseModel):
    auth_type: typing.Literal["ip_allowlist"] = "ip_allowlist"
    cidrs: typing.List[str]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


IncomingWebhookAuthResponse = typing_extensions.Annotated[
    typing.Union[
        IncomingWebhookAuthResponse_None,
        IncomingWebhookAuthResponse_All,
        IncomingWebhookAuthResponse_Any,
        IncomingWebhookAuthResponse_Hmac,
        IncomingWebhookAuthResponse_HeaderEquals,
        IncomingWebhookAuthResponse_QueryEquals,
        IncomingWebhookAuthResponse_Basic,
        IncomingWebhookAuthResponse_BearerStatic,
        IncomingWebhookAuthResponse_Jwt,
        IncomingWebhookAuthResponse_IpAllowlist,
    ],
    pydantic.Field(discriminator="auth_type"),
]
