# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .auth_method import AuthMethod
from .integration_level import IntegrationLevel


class IntegrationStatus(UniversalBaseModel):
    """
    Status of a single integration (for list view).

    ``provider`` is the stable identifier (preset id or custom slug).
    ``display_name`` carries the human-readable label for customs (the
    free-form text the creator typed); presets surface their static name
    via the frontend's preset catalog so this stays None for them.
    """

    auth_method: typing.Optional[AuthMethod] = None
    connected: bool
    display_name: typing.Optional[str] = None
    level: typing.Optional[IntegrationLevel] = None
    preset_id: typing.Optional[str] = None
    provider: str

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
