# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel


class IntegrationProvider(UniversalBaseModel):
    """
    Information about an available provider.
    """

    name: str
    hosts: typing.List[str]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
