# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .integration_status import IntegrationStatus


class IntegrationListResponse(UniversalBaseModel):
    """
    List of integrations (both user and tenant level).
    """

    integrations: typing.List[IntegrationStatus]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
