# This file was auto-generated by Fern from our API Definition.

import typing

from ..core import enum

T_Result = typing.TypeVar("T_Result")


class IsloErrorCode(enum.StrEnum):
    """
    Machine-readable error codes for API responses.
    """

    AUTH_REQUIRED = "AUTH_REQUIRED"
    AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"
    AUTH_TOKEN_INVALID = "AUTH_TOKEN_INVALID"
    ACCESS_DENIED = "ACCESS_DENIED"
    RESOURCE_UNAVAILABLE = "RESOURCE_UNAVAILABLE"
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    RATE_LIMITED = "RATE_LIMITED"
    INSUFFICIENT_CREDITS = "INSUFFICIENT_CREDITS"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    INVALID_REQUEST = "INVALID_REQUEST"
    UPSTREAM_ERROR = "UPSTREAM_ERROR"
    UPSTREAM_TIMEOUT = "UPSTREAM_TIMEOUT"
    UPSTREAM_UNAVAILABLE = "UPSTREAM_UNAVAILABLE"
    TIMEOUT = "TIMEOUT"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    _UNKNOWN = "__ISLOERRORCODE_UNKNOWN__"
    """
    This member is used for forward compatibility. If the value is not recognized by the enum, it will be stored here, and the raw value is accessible through `.value`.
    """

    @classmethod
    def _missing_(cls, value: typing.Any) -> "IsloErrorCode":
        unknown = cls._UNKNOWN
        unknown._value_ = value
        return unknown

    def visit(
        self,
        auth_required: typing.Callable[[], T_Result],
        auth_token_expired: typing.Callable[[], T_Result],
        auth_token_invalid: typing.Callable[[], T_Result],
        access_denied: typing.Callable[[], T_Result],
        resource_unavailable: typing.Callable[[], T_Result],
        resource_not_found: typing.Callable[[], T_Result],
        rate_limited: typing.Callable[[], T_Result],
        insufficient_credits: typing.Callable[[], T_Result],
        validation_error: typing.Callable[[], T_Result],
        invalid_request: typing.Callable[[], T_Result],
        upstream_error: typing.Callable[[], T_Result],
        upstream_timeout: typing.Callable[[], T_Result],
        upstream_unavailable: typing.Callable[[], T_Result],
        timeout: typing.Callable[[], T_Result],
        internal_error: typing.Callable[[], T_Result],
        _unknown_member: typing.Callable[[str], T_Result],
    ) -> T_Result:
        if self is IsloErrorCode.AUTH_REQUIRED:
            return auth_required()
        if self is IsloErrorCode.AUTH_TOKEN_EXPIRED:
            return auth_token_expired()
        if self is IsloErrorCode.AUTH_TOKEN_INVALID:
            return auth_token_invalid()
        if self is IsloErrorCode.ACCESS_DENIED:
            return access_denied()
        if self is IsloErrorCode.RESOURCE_UNAVAILABLE:
            return resource_unavailable()
        if self is IsloErrorCode.RESOURCE_NOT_FOUND:
            return resource_not_found()
        if self is IsloErrorCode.RATE_LIMITED:
            return rate_limited()
        if self is IsloErrorCode.INSUFFICIENT_CREDITS:
            return insufficient_credits()
        if self is IsloErrorCode.VALIDATION_ERROR:
            return validation_error()
        if self is IsloErrorCode.INVALID_REQUEST:
            return invalid_request()
        if self is IsloErrorCode.UPSTREAM_ERROR:
            return upstream_error()
        if self is IsloErrorCode.UPSTREAM_TIMEOUT:
            return upstream_timeout()
        if self is IsloErrorCode.UPSTREAM_UNAVAILABLE:
            return upstream_unavailable()
        if self is IsloErrorCode.TIMEOUT:
            return timeout()
        if self is IsloErrorCode.INTERNAL_ERROR:
            return internal_error()
        return _unknown_member(self._value_)
