# This file was auto-generated by Fern from our API Definition.

import typing

from ..core import enum

T_Result = typing.TypeVar("T_Result")


class JobOutputSpecType(enum.StrEnum):
    STRING = "string"
    INTEGER = "integer"
    NUMBER = "number"
    BOOLEAN = "boolean"
    OBJECT = "object"
    ARRAY = "array"
    _UNKNOWN = "__JOBOUTPUTSPECTYPE_UNKNOWN__"
    """
    This member is used for forward compatibility. If the value is not recognized by the enum, it will be stored here, and the raw value is accessible through `.value`.
    """

    @classmethod
    def _missing_(cls, value: typing.Any) -> "JobOutputSpecType":
        unknown = cls._UNKNOWN
        unknown._value_ = value
        return unknown

    def visit(
        self,
        string: typing.Callable[[], T_Result],
        integer: typing.Callable[[], T_Result],
        number: typing.Callable[[], T_Result],
        boolean: typing.Callable[[], T_Result],
        object: typing.Callable[[], T_Result],
        array: typing.Callable[[], T_Result],
        _unknown_member: typing.Callable[[str], T_Result],
    ) -> T_Result:
        if self is JobOutputSpecType.STRING:
            return string()
        if self is JobOutputSpecType.INTEGER:
            return integer()
        if self is JobOutputSpecType.NUMBER:
            return number()
        if self is JobOutputSpecType.BOOLEAN:
            return boolean()
        if self is JobOutputSpecType.OBJECT:
            return object()
        if self is JobOutputSpecType.ARRAY:
            return array()
        return _unknown_member(self._value_)
