# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel


class JobVersionResponse(UniversalBaseModel):
    id: str
    version_number: int
    content_hash: str
    deployed_at: dt.datetime
    manifest: typing.Dict[str, typing.Any]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
