# This file was auto-generated by Fern from our API Definition.

import typing

from .job_param_spec_type_one import JobParamSpecTypeOne
from .job_param_spec_type_zero import JobParamSpecTypeZero

JobParamSpecType = typing.Union[JobParamSpecTypeZero, JobParamSpecTypeOne]
