# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .knowledge_level import KnowledgeLevel
from .knowledge_link_response import KnowledgeLinkResponse


class KnowledgeVersionResponse(UniversalBaseModel):
    id: str
    version_number: int
    level: KnowledgeLevel
    format: str
    body: str
    metadata: typing.Dict[str, typing.Any]
    links: typing.List[KnowledgeLinkResponse]
    content_hash: str
    created_at: dt.datetime

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
