# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .knowledge_level import KnowledgeLevel
from .knowledge_link_response import KnowledgeLinkResponse
from .knowledge_status import KnowledgeStatus


class KnowledgeItemListResponse(UniversalBaseModel):
    id: str
    slug: str = pydantic.Field()
    """
    Unique lowercase identifier (letters, digits, hyphens). Set at creation and cannot be changed.
    """

    level: KnowledgeLevel
    status: KnowledgeStatus
    links: typing.List[KnowledgeLinkResponse]
    created_at: dt.datetime
    updated_at: dt.datetime
    version_number: typing.Optional[int] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
