# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .knowledge_level import KnowledgeLevel
from .knowledge_link_input import KnowledgeLinkInput


class KnowledgeItemCreate(UniversalBaseModel):
    body: typing.Optional[str] = None
    format: typing.Optional[str] = None
    level: typing.Optional[KnowledgeLevel] = None
    links: typing.Optional[typing.List[KnowledgeLinkInput]] = None
    metadata: typing.Optional[typing.Dict[str, typing.Any]] = None
    slug: str = pydantic.Field()
    """
    Unique lowercase identifier (letters, digits, hyphens). Set at creation and cannot be changed.
    """

    type: typing.Optional[KnowledgeLevel] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
