# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel


class LineRunSteerRequest(UniversalBaseModel):
    params: typing.Optional[typing.Dict[str, typing.Any]] = None
    reason: typing.Optional[str] = None
    reset_iterations: typing.Optional[bool] = None
    stage_name: str

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
