# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel, update_forward_refs
from ..core.serialization import FieldMetadata
from .agentic_transition_option import AgenticTransitionOption
from .agentic_transition_output_instructions import AgenticTransitionOutputInstructions
from .conditional_transition_output_params_value import ConditionalTransitionOutputParamsValue


class LineManifestOutputTransitionsItem_Agentic(UniversalBaseModel):
    type: typing.Literal["agentic"] = "agentic"
    id: str
    from_: typing_extensions.Annotated[str, FieldMetadata(alias="from"), pydantic.Field(alias="from")]
    instructions: AgenticTransitionOutputInstructions
    options: typing.Optional[typing.List[AgenticTransitionOption]] = None
    label: typing.Optional[str] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class LineManifestOutputTransitionsItem_Conditional(UniversalBaseModel):
    type: typing.Literal["conditional"] = "conditional"
    id: str
    from_: typing_extensions.Annotated[str, FieldMetadata(alias="from"), pydantic.Field(alias="from")]
    to: str
    when: "LineConditionOutput"
    label: typing.Optional[str] = None
    max_iterations: typing.Optional[int] = None
    params: typing.Optional[typing.Dict[str, ConditionalTransitionOutputParamsValue]] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


LineManifestOutputTransitionsItem = typing_extensions.Annotated[
    typing.Union[LineManifestOutputTransitionsItem_Agentic, LineManifestOutputTransitionsItem_Conditional],
    pydantic.Field(discriminator="type"),
]
from .compound_condition_output import CompoundConditionOutput  # noqa: E402, I001
from .line_condition_output import LineConditionOutput  # noqa: E402, I001
from .not_condition_output import NotConditionOutput  # noqa: E402, I001

update_forward_refs(
    LineManifestOutputTransitionsItem_Conditional,
    CompoundConditionOutput=CompoundConditionOutput,
    LineConditionOutput=LineConditionOutput,
    NotConditionOutput=NotConditionOutput,
)
