# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel, update_forward_refs
from ..core.serialization import FieldMetadata
from .agentic_transition_input_instructions import AgenticTransitionInputInstructions
from .agentic_transition_option import AgenticTransitionOption
from .conditional_transition_input_params_value import ConditionalTransitionInputParamsValue


class LineManifestInputTransitionsItem_Agentic(UniversalBaseModel):
    type: typing.Literal["agentic"] = "agentic"
    id: str
    from_: typing_extensions.Annotated[str, FieldMetadata(alias="from"), pydantic.Field(alias="from")]
    instructions: AgenticTransitionInputInstructions
    options: typing.Optional[typing.List[AgenticTransitionOption]] = None
    label: typing.Optional[str] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class LineManifestInputTransitionsItem_Conditional(UniversalBaseModel):
    type: typing.Literal["conditional"] = "conditional"
    id: str
    from_: typing_extensions.Annotated[str, FieldMetadata(alias="from"), pydantic.Field(alias="from")]
    to: str
    when: "LineConditionInput"
    label: typing.Optional[str] = None
    max_iterations: typing.Optional[int] = None
    params: typing.Optional[typing.Dict[str, ConditionalTransitionInputParamsValue]] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


LineManifestInputTransitionsItem = typing_extensions.Annotated[
    typing.Union[LineManifestInputTransitionsItem_Agentic, LineManifestInputTransitionsItem_Conditional],
    pydantic.Field(discriminator="type"),
]
from .compound_condition_input import CompoundConditionInput  # noqa: E402, I001
from .line_condition_input import LineConditionInput  # noqa: E402, I001
from .not_condition_input import NotConditionInput  # noqa: E402, I001

update_forward_refs(
    LineManifestInputTransitionsItem_Conditional,
    CompoundConditionInput=CompoundConditionInput,
    LineConditionInput=LineConditionInput,
    NotConditionInput=NotConditionInput,
)
