# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel


class LineEventResponse(UniversalBaseModel):
    created_at: dt.datetime
    event_type: str
    id: str
    payload: typing.Optional[typing.Dict[str, typing.Any]] = None
    sequence: int

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
