# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel


class LineRunCreate(UniversalBaseModel):
    version_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Deployed line version to run; defaults to latest
    """

    region: typing.Optional[str] = pydantic.Field(default=None)
    """
    Compute region override
    """

    params: typing.Optional[typing.Dict[str, typing.Any]] = None
    trigger_payload: typing.Optional[typing.Dict[str, typing.Any]] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
