# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel, update_forward_refs
from .condition_operand import ConditionOperand


class LineConditionOutput_All(UniversalBaseModel):
    op: typing.Literal["all"] = "all"
    conditions: typing.List["LineConditionOutput"]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class LineConditionOutput_Always(UniversalBaseModel):
    op: typing.Literal["always"] = "always"

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class LineConditionOutput_Any(UniversalBaseModel):
    op: typing.Literal["any"] = "any"
    conditions: typing.List["LineConditionOutput"]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class LineConditionOutput_Contains(UniversalBaseModel):
    op: typing.Literal["contains"] = "contains"
    left: ConditionOperand
    right: ConditionOperand

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class LineConditionOutput_Eq(UniversalBaseModel):
    op: typing.Literal["eq"] = "eq"
    left: ConditionOperand
    right: ConditionOperand

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class LineConditionOutput_Exists(UniversalBaseModel):
    op: typing.Literal["exists"] = "exists"
    operand: ConditionOperand

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class LineConditionOutput_Falsy(UniversalBaseModel):
    op: typing.Literal["falsy"] = "falsy"
    operand: ConditionOperand

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class LineConditionOutput_Missing(UniversalBaseModel):
    op: typing.Literal["missing"] = "missing"
    operand: ConditionOperand

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class LineConditionOutput_Ne(UniversalBaseModel):
    op: typing.Literal["ne"] = "ne"
    left: ConditionOperand
    right: ConditionOperand

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class LineConditionOutput_Not(UniversalBaseModel):
    op: typing.Literal["not"] = "not"
    condition: "LineConditionOutput"

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class LineConditionOutput_NotContains(UniversalBaseModel):
    op: typing.Literal["not_contains"] = "not_contains"
    left: ConditionOperand
    right: ConditionOperand

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class LineConditionOutput_Truthy(UniversalBaseModel):
    op: typing.Literal["truthy"] = "truthy"
    operand: ConditionOperand

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


LineConditionOutput = typing_extensions.Annotated[
    typing.Union[
        LineConditionOutput_All,
        LineConditionOutput_Always,
        LineConditionOutput_Any,
        LineConditionOutput_Contains,
        LineConditionOutput_Eq,
        LineConditionOutput_Exists,
        LineConditionOutput_Falsy,
        LineConditionOutput_Missing,
        LineConditionOutput_Ne,
        LineConditionOutput_Not,
        LineConditionOutput_NotContains,
        LineConditionOutput_Truthy,
    ],
    pydantic.Field(discriminator="op"),
]
from .not_condition_output import NotConditionOutput  # noqa: E402, I001
from .compound_condition_output import CompoundConditionOutput  # noqa: E402, I001

update_forward_refs(
    LineConditionOutput_All, LineConditionOutput=LineConditionOutput, NotConditionOutput=NotConditionOutput
)
update_forward_refs(
    LineConditionOutput_Any, LineConditionOutput=LineConditionOutput, NotConditionOutput=NotConditionOutput
)
update_forward_refs(
    LineConditionOutput_Not, CompoundConditionOutput=CompoundConditionOutput, LineConditionOutput=LineConditionOutput
)
