# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel, update_forward_refs
from .integration_trigger_section_output_selector import IntegrationTriggerSectionOutputSelector
from .trigger_path_binding import TriggerPathBinding


class LineManifestOutputTrigger_IntegrationTrigger(UniversalBaseModel):
    type: typing.Literal["integration_trigger"] = "integration_trigger"
    provider: str
    name: str
    selector: IntegrationTriggerSectionOutputSelector
    filters: typing.Optional[typing.List["LineConditionOutput"]] = None
    outputs: typing.Optional[typing.Dict[str, TriggerPathBinding]] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class LineManifestOutputTrigger_Manual(UniversalBaseModel):
    type: typing.Literal["manual"] = "manual"

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class LineManifestOutputTrigger_Schedule(UniversalBaseModel):
    type: typing.Literal["schedule"] = "schedule"
    cron: str
    timezone: typing.Optional[str] = None
    inputs: typing.Optional[typing.Dict[str, typing.Any]] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class LineManifestOutputTrigger_Webhook(UniversalBaseModel):
    type: typing.Literal["webhook"] = "webhook"
    path: str

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


LineManifestOutputTrigger = typing_extensions.Annotated[
    typing.Union[
        LineManifestOutputTrigger_IntegrationTrigger,
        LineManifestOutputTrigger_Manual,
        LineManifestOutputTrigger_Schedule,
        LineManifestOutputTrigger_Webhook,
    ],
    pydantic.Field(discriminator="type"),
]
from .compound_condition_output import CompoundConditionOutput  # noqa: E402, I001
from .line_condition_output import LineConditionOutput  # noqa: E402, I001
from .not_condition_output import NotConditionOutput  # noqa: E402, I001

update_forward_refs(
    LineManifestOutputTrigger_IntegrationTrigger,
    CompoundConditionOutput=CompoundConditionOutput,
    LineConditionOutput=LineConditionOutput,
    NotConditionOutput=NotConditionOutput,
)
