# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel


class LinearExternalRef(UniversalBaseModel):
    """
    Linear identity: issues use id or identifier; comments use id.
    """

    kind: typing.Optional[str] = None
    id: typing.Optional[str] = None
    identifier: typing.Optional[str] = None
    team: typing.Optional[str] = None
    issue_id: typing.Optional[str] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
