# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .line_run_debug_stage import LineRunDebugStage
from .line_run_failure_summary import LineRunFailureSummary


class LineRunDebugResponse(UniversalBaseModel):
    id: str
    line_name: str
    line_version_id: typing.Optional[str] = None
    status: str
    triggered_by: str
    region: typing.Optional[str] = None
    started_at: typing.Optional[dt.datetime] = None
    completed_at: typing.Optional[dt.datetime] = None
    error_message: typing.Optional[str] = None
    failure_summary: typing.Optional[LineRunFailureSummary] = None
    stages: typing.Optional[typing.List[LineRunDebugStage]] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
