# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .line_event_response import LineEventResponse


class LineEventPage(UniversalBaseModel):
    items: typing.Optional[typing.List[LineEventResponse]] = None
    total: typing.Optional[int] = None
    has_more: typing.Optional[bool] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
