# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .knowledge_version_list_response import KnowledgeVersionListResponse


class ListPageKnowledgeVersionListResponse(UniversalBaseModel):
    items: typing.List[KnowledgeVersionListResponse]
    next_cursor: typing.Optional[str] = None
    total: typing.Optional[int] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
