# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .agent_session_list_item_response import AgentSessionListItemResponse


class ListPageAgentSessionListItemResponse(UniversalBaseModel):
    items: typing.List[AgentSessionListItemResponse]
    next_cursor: typing.Optional[str] = None
    total: typing.Optional[int] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
