# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel, update_forward_refs
from .line_response import LineResponse


class ListPageLineResponse(UniversalBaseModel):
    items: typing.List[LineResponse]
    next_cursor: typing.Optional[str] = None
    total: typing.Optional[int] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


update_forward_refs(ListPageLineResponse)
