# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel


class MachineSchedule(UniversalBaseModel):
    cron: typing.Optional[str] = None
    enabled: typing.Optional[bool] = None
    timezone: typing.Optional[str] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
