# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel


class ManagerTurnSummary(UniversalBaseModel):
    """
    One manager turn, projected for a list row.
    """

    started_at: typing.Optional[dt.datetime] = None
    state: str
    workflow_run_id: str

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
