# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .regex_content_filter_direction import RegexContentFilterDirection


class RegexContentFilter(UniversalBaseModel):
    direction: RegexContentFilterDirection
    pattern: str

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
