# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel


class RunAgentSessionStepActionResumePrompt_Knowledge(UniversalBaseModel):
    type: typing.Literal["knowledge"] = "knowledge"
    slug: str

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class RunAgentSessionStepActionResumePrompt_Literal(UniversalBaseModel):
    type: typing.Literal["literal"] = "literal"
    value: typing.Any

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


RunAgentSessionStepActionResumePrompt = typing_extensions.Annotated[
    typing.Union[RunAgentSessionStepActionResumePrompt_Knowledge, RunAgentSessionStepActionResumePrompt_Literal],
    pydantic.Field(discriminator="type"),
]
