# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .init_capability import InitCapability


class SandboxInitCustom(UniversalBaseModel):
    capabilities: typing.List[InitCapability]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
