# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from .knowledge_binding import KnowledgeBinding
from .run_agent_exec_step_action_command import RunAgentExecStepActionCommand
from .run_agent_exec_step_action_harness import RunAgentExecStepActionHarness
from .run_agent_session_step_action_command import RunAgentSessionStepActionCommand
from .run_agent_session_step_action_harness import RunAgentSessionStepActionHarness
from .run_agent_session_step_action_prompt import RunAgentSessionStepActionPrompt
from .run_agent_session_step_action_resume_prompt import RunAgentSessionStepActionResumePrompt


class TaskStepInputRunAgent_Exec(UniversalBaseModel):
    mode: typing.Literal["exec"] = "exec"
    harness: RunAgentExecStepActionHarness
    command: RunAgentExecStepActionCommand
    model: typing.Optional[str] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class TaskStepInputRunAgent_Session(UniversalBaseModel):
    mode: typing.Literal["session"] = "session"
    harness: RunAgentSessionStepActionHarness
    model: typing.Optional[str] = None
    prompt: typing.Optional[RunAgentSessionStepActionPrompt] = None
    resume_prompt: typing.Optional[RunAgentSessionStepActionResumePrompt] = None
    knowledge: typing.Optional[typing.List[KnowledgeBinding]] = None
    session: typing.Optional[str] = None
    command: typing.Optional[RunAgentSessionStepActionCommand] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


TaskStepInputRunAgent = typing_extensions.Annotated[
    typing.Union[TaskStepInputRunAgent_Exec, TaskStepInputRunAgent_Session], pydantic.Field(discriminator="mode")
]
