# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel


class TokenResponse(UniversalBaseModel):
    """
    Response containing the session JWT.
    """

    session_token: str = pydantic.Field()
    """
    Descope session JWT
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
