# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel


class TriggerSummary(UniversalBaseModel):
    """
    What set a run off.

    `provider`, `event_name`, and `delivery_id` are lifted out of the nested
    `payload.trigger` object so a list row is readable without walking the
    envelope. The extracted trigger values are not repeated here; they land in
    the run's `run_params`. `payload` still carries the whole envelope, minus the
    raw webhook body on list responses.
    """

    delivery_id: typing.Optional[str] = None
    event_name: typing.Optional[str] = None
    payload: typing.Optional[typing.Dict[str, typing.Any]] = None
    provider: typing.Optional[str] = None
    source: str

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
