# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel


class TriggerEventEffect(UniversalBaseModel):
    delivery_id: str
    factory: typing.Optional[str] = None
    factory_id: typing.Optional[str] = None
    failure_code: typing.Optional[str] = None
    failure_summary: typing.Optional[str] = None
    line: typing.Optional[str] = None
    line_id: typing.Optional[str] = None
    line_run_id: typing.Optional[str] = None
    line_version: typing.Optional[int] = None
    line_version_id: typing.Optional[str] = None
    status: str

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
