# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .verification_gate import VerificationGate


class VerificationSection(UniversalBaseModel):
    enabled: typing.Optional[bool] = None
    gate: typing.Optional[VerificationGate] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
