# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import UniversalBaseModel
from ...types.content_type_content_filter_direction import ContentTypeContentFilterDirection
from ...types.judge_content_filter_direction import JudgeContentFilterDirection
from ...types.judge_content_filter_fallback import JudgeContentFilterFallback
from ...types.judge_content_filter_provider_key import JudgeContentFilterProviderKey
from ...types.regex_content_filter_direction import RegexContentFilterDirection
from ...types.size_limit_content_filter_direction import SizeLimitContentFilterDirection


class GatewayRuleCreateContentFilter_ContentType(UniversalBaseModel):
    filter_type: typing.Literal["content_type"] = "content_type"
    direction: ContentTypeContentFilterDirection
    pattern: str

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class GatewayRuleCreateContentFilter_Judge(UniversalBaseModel):
    filter_type: typing.Literal["judge"] = "judge"
    direction: JudgeContentFilterDirection
    name: str
    provider_key: JudgeContentFilterProviderKey
    model: str
    prompt: str
    fallback: typing.Optional[JudgeContentFilterFallback] = None
    timeout_seconds: typing.Optional[int] = None
    max_tokens: typing.Optional[int] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class GatewayRuleCreateContentFilter_Regex(UniversalBaseModel):
    filter_type: typing.Literal["regex"] = "regex"
    direction: RegexContentFilterDirection
    pattern: str

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class GatewayRuleCreateContentFilter_SizeLimit(UniversalBaseModel):
    filter_type: typing.Literal["size_limit"] = "size_limit"
    direction: SizeLimitContentFilterDirection
    pattern: str

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


GatewayRuleCreateContentFilter = typing_extensions.Annotated[
    typing.Union[
        GatewayRuleCreateContentFilter_ContentType,
        GatewayRuleCreateContentFilter_Judge,
        GatewayRuleCreateContentFilter_Regex,
        GatewayRuleCreateContentFilter_SizeLimit,
    ],
    pydantic.Field(discriminator="filter_type"),
]
