# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.conflict_error import ConflictError
from ..errors.forbidden_error import ForbiddenError
from ..errors.not_found_error import NotFoundError
from ..errors.unauthorized_error import UnauthorizedError
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.auth_strategy_schema import AuthStrategySchema
from ..types.error_response import ErrorResponse
from ..types.gateway_action import GatewayAction
from ..types.gateway_profile_detail_response import GatewayProfileDetailResponse
from ..types.gateway_profile_response import GatewayProfileResponse
from ..types.gateway_rule_response import GatewayRuleResponse
from ..types.list_page_gateway_profile_response import ListPageGatewayProfileResponse
from ..types.rule_reorder_item import RuleReorderItem
from .types.gateway_profile_create_integration_policy import GatewayProfileCreateIntegrationPolicy
from .types.gateway_profile_update_integration_policy import GatewayProfileUpdateIntegrationPolicy
from .types.gateway_rule_create_content_filter import GatewayRuleCreateContentFilter
from .types.gateway_rule_update_content_filter import GatewayRuleUpdateContentFilter
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawGatewayProfilesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list_gateway_profiles(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[ListPageGatewayProfileResponse]:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ListPageGatewayProfileResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "gateway/profiles",
            base_url=self._client_wrapper.get_environment().control,
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListPageGatewayProfileResponse,
                    parse_obj_as(
                        type_=ListPageGatewayProfileResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create_gateway_profile(
        self,
        *,
        name: str,
        cloud_role: typing.Optional[str] = OMIT,
        default_action: typing.Optional[GatewayAction] = OMIT,
        description: typing.Optional[str] = OMIT,
        integration_policy: typing.Optional[GatewayProfileCreateIntegrationPolicy] = OMIT,
        internet_enabled: typing.Optional[bool] = OMIT,
        is_default: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[GatewayProfileResponse]:
        """
        Parameters
        ----------
        name : str

        cloud_role : typing.Optional[str]
            Cloud role public ID (UUID)

        default_action : typing.Optional[GatewayAction]

        description : typing.Optional[str]

        integration_policy : typing.Optional[GatewayProfileCreateIntegrationPolicy]

        internet_enabled : typing.Optional[bool]

        is_default : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[GatewayProfileResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "gateway/profiles",
            base_url=self._client_wrapper.get_environment().control,
            method="POST",
            json={
                "cloud_role": cloud_role,
                "default_action": default_action,
                "description": description,
                "integration_policy": convert_and_respect_annotation_metadata(
                    object_=integration_policy, annotation=GatewayProfileCreateIntegrationPolicy, direction="write"
                ),
                "internet_enabled": internet_enabled,
                "is_default": is_default,
                "name": name,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GatewayProfileResponse,
                    parse_obj_as(
                        type_=GatewayProfileResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_gateway_profile(
        self, profile_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[GatewayProfileDetailResponse]:
        """
        Parameters
        ----------
        profile_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[GatewayProfileDetailResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"gateway/profiles/{encode_path_param(profile_id)}",
            base_url=self._client_wrapper.get_environment().control,
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GatewayProfileDetailResponse,
                    parse_obj_as(
                        type_=GatewayProfileDetailResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def delete_gateway_profile(
        self, profile_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[None]:
        """
        Parameters
        ----------
        profile_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[None]
        """
        _response = self._client_wrapper.httpx_client.request(
            f"gateway/profiles/{encode_path_param(profile_id)}",
            base_url=self._client_wrapper.get_environment().control,
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return HttpResponse(response=_response, data=None)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def update_gateway_profile(
        self,
        profile_id: str,
        *,
        cloud_role: typing.Optional[str] = OMIT,
        default_action: typing.Optional[GatewayAction] = OMIT,
        description: typing.Optional[str] = OMIT,
        integration_policy: typing.Optional[GatewayProfileUpdateIntegrationPolicy] = OMIT,
        internet_enabled: typing.Optional[bool] = OMIT,
        is_default: typing.Optional[bool] = OMIT,
        name: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[GatewayProfileResponse]:
        """
        Parameters
        ----------
        profile_id : str

        cloud_role : typing.Optional[str]
            Cloud role public ID (UUID), empty string to unset

        default_action : typing.Optional[GatewayAction]

        description : typing.Optional[str]

        integration_policy : typing.Optional[GatewayProfileUpdateIntegrationPolicy]
            Omit to leave unchanged; send {"mode": "all"} to allow all integrations

        internet_enabled : typing.Optional[bool]

        is_default : typing.Optional[bool]

        name : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[GatewayProfileResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"gateway/profiles/{encode_path_param(profile_id)}",
            base_url=self._client_wrapper.get_environment().control,
            method="PATCH",
            json={
                "cloud_role": cloud_role,
                "default_action": default_action,
                "description": description,
                "integration_policy": convert_and_respect_annotation_metadata(
                    object_=integration_policy,
                    annotation=typing.Optional[GatewayProfileUpdateIntegrationPolicy],
                    direction="write",
                ),
                "internet_enabled": internet_enabled,
                "is_default": is_default,
                "name": name,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GatewayProfileResponse,
                    parse_obj_as(
                        type_=GatewayProfileResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create_gateway_rule(
        self,
        profile_id: str,
        *,
        host_pattern: str,
        action: typing.Optional[GatewayAction] = OMIT,
        auth_strategy: typing.Optional[AuthStrategySchema] = OMIT,
        content_filter: typing.Optional[GatewayRuleCreateContentFilter] = OMIT,
        methods: typing.Optional[typing.Sequence[str]] = OMIT,
        path_pattern: typing.Optional[str] = OMIT,
        priority: typing.Optional[int] = OMIT,
        provider_key: typing.Optional[str] = OMIT,
        rate_limit_rpm: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[GatewayRuleResponse]:
        """
        Parameters
        ----------
        profile_id : str

        host_pattern : str

        action : typing.Optional[GatewayAction]

        auth_strategy : typing.Optional[AuthStrategySchema]

        content_filter : typing.Optional[GatewayRuleCreateContentFilter]

        methods : typing.Optional[typing.Sequence[str]]

        path_pattern : typing.Optional[str]

        priority : typing.Optional[int]

        provider_key : typing.Optional[str]

        rate_limit_rpm : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[GatewayRuleResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"gateway/profiles/{encode_path_param(profile_id)}/rules",
            base_url=self._client_wrapper.get_environment().control,
            method="POST",
            json={
                "action": action,
                "auth_strategy": convert_and_respect_annotation_metadata(
                    object_=auth_strategy, annotation=typing.Optional[AuthStrategySchema], direction="write"
                ),
                "content_filter": convert_and_respect_annotation_metadata(
                    object_=content_filter,
                    annotation=typing.Optional[GatewayRuleCreateContentFilter],
                    direction="write",
                ),
                "host_pattern": host_pattern,
                "methods": methods,
                "path_pattern": path_pattern,
                "priority": priority,
                "provider_key": provider_key,
                "rate_limit_rpm": rate_limit_rpm,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GatewayRuleResponse,
                    parse_obj_as(
                        type_=GatewayRuleResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def reorder_gateway_rules(
        self,
        profile_id: str,
        *,
        rules: typing.Sequence[RuleReorderItem],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[typing.List[GatewayRuleResponse]]:
        """
        Parameters
        ----------
        profile_id : str

        rules : typing.Sequence[RuleReorderItem]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.List[GatewayRuleResponse]]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"gateway/profiles/{encode_path_param(profile_id)}/rules/reorder",
            base_url=self._client_wrapper.get_environment().control,
            method="POST",
            json={
                "rules": convert_and_respect_annotation_metadata(
                    object_=rules, annotation=typing.Sequence[RuleReorderItem], direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[GatewayRuleResponse],
                    parse_obj_as(
                        type_=typing.List[GatewayRuleResponse],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def delete_gateway_rule(
        self, profile_id: str, rule_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[None]:
        """
        Parameters
        ----------
        profile_id : str

        rule_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[None]
        """
        _response = self._client_wrapper.httpx_client.request(
            f"gateway/profiles/{encode_path_param(profile_id)}/rules/{encode_path_param(rule_id)}",
            base_url=self._client_wrapper.get_environment().control,
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return HttpResponse(response=_response, data=None)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def update_gateway_rule(
        self,
        profile_id: str,
        rule_id: str,
        *,
        action: typing.Optional[GatewayAction] = OMIT,
        auth_strategy: typing.Optional[AuthStrategySchema] = OMIT,
        content_filter: typing.Optional[GatewayRuleUpdateContentFilter] = OMIT,
        host_pattern: typing.Optional[str] = OMIT,
        methods: typing.Optional[typing.Sequence[str]] = OMIT,
        path_pattern: typing.Optional[str] = OMIT,
        priority: typing.Optional[int] = OMIT,
        provider_key: typing.Optional[str] = OMIT,
        rate_limit_rpm: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[GatewayRuleResponse]:
        """
        Parameters
        ----------
        profile_id : str

        rule_id : str

        action : typing.Optional[GatewayAction]

        auth_strategy : typing.Optional[AuthStrategySchema]

        content_filter : typing.Optional[GatewayRuleUpdateContentFilter]

        host_pattern : typing.Optional[str]

        methods : typing.Optional[typing.Sequence[str]]

        path_pattern : typing.Optional[str]

        priority : typing.Optional[int]

        provider_key : typing.Optional[str]

        rate_limit_rpm : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[GatewayRuleResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"gateway/profiles/{encode_path_param(profile_id)}/rules/{encode_path_param(rule_id)}",
            base_url=self._client_wrapper.get_environment().control,
            method="PATCH",
            json={
                "action": action,
                "auth_strategy": convert_and_respect_annotation_metadata(
                    object_=auth_strategy, annotation=typing.Optional[AuthStrategySchema], direction="write"
                ),
                "content_filter": convert_and_respect_annotation_metadata(
                    object_=content_filter,
                    annotation=typing.Optional[GatewayRuleUpdateContentFilter],
                    direction="write",
                ),
                "host_pattern": host_pattern,
                "methods": methods,
                "path_pattern": path_pattern,
                "priority": priority,
                "provider_key": provider_key,
                "rate_limit_rpm": rate_limit_rpm,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GatewayRuleResponse,
                    parse_obj_as(
                        type_=GatewayRuleResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawGatewayProfilesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list_gateway_profiles(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[ListPageGatewayProfileResponse]:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ListPageGatewayProfileResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "gateway/profiles",
            base_url=self._client_wrapper.get_environment().control,
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListPageGatewayProfileResponse,
                    parse_obj_as(
                        type_=ListPageGatewayProfileResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create_gateway_profile(
        self,
        *,
        name: str,
        cloud_role: typing.Optional[str] = OMIT,
        default_action: typing.Optional[GatewayAction] = OMIT,
        description: typing.Optional[str] = OMIT,
        integration_policy: typing.Optional[GatewayProfileCreateIntegrationPolicy] = OMIT,
        internet_enabled: typing.Optional[bool] = OMIT,
        is_default: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[GatewayProfileResponse]:
        """
        Parameters
        ----------
        name : str

        cloud_role : typing.Optional[str]
            Cloud role public ID (UUID)

        default_action : typing.Optional[GatewayAction]

        description : typing.Optional[str]

        integration_policy : typing.Optional[GatewayProfileCreateIntegrationPolicy]

        internet_enabled : typing.Optional[bool]

        is_default : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[GatewayProfileResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "gateway/profiles",
            base_url=self._client_wrapper.get_environment().control,
            method="POST",
            json={
                "cloud_role": cloud_role,
                "default_action": default_action,
                "description": description,
                "integration_policy": convert_and_respect_annotation_metadata(
                    object_=integration_policy, annotation=GatewayProfileCreateIntegrationPolicy, direction="write"
                ),
                "internet_enabled": internet_enabled,
                "is_default": is_default,
                "name": name,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GatewayProfileResponse,
                    parse_obj_as(
                        type_=GatewayProfileResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_gateway_profile(
        self, profile_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[GatewayProfileDetailResponse]:
        """
        Parameters
        ----------
        profile_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[GatewayProfileDetailResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"gateway/profiles/{encode_path_param(profile_id)}",
            base_url=self._client_wrapper.get_environment().control,
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GatewayProfileDetailResponse,
                    parse_obj_as(
                        type_=GatewayProfileDetailResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def delete_gateway_profile(
        self, profile_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[None]:
        """
        Parameters
        ----------
        profile_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[None]
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"gateway/profiles/{encode_path_param(profile_id)}",
            base_url=self._client_wrapper.get_environment().control,
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return AsyncHttpResponse(response=_response, data=None)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def update_gateway_profile(
        self,
        profile_id: str,
        *,
        cloud_role: typing.Optional[str] = OMIT,
        default_action: typing.Optional[GatewayAction] = OMIT,
        description: typing.Optional[str] = OMIT,
        integration_policy: typing.Optional[GatewayProfileUpdateIntegrationPolicy] = OMIT,
        internet_enabled: typing.Optional[bool] = OMIT,
        is_default: typing.Optional[bool] = OMIT,
        name: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[GatewayProfileResponse]:
        """
        Parameters
        ----------
        profile_id : str

        cloud_role : typing.Optional[str]
            Cloud role public ID (UUID), empty string to unset

        default_action : typing.Optional[GatewayAction]

        description : typing.Optional[str]

        integration_policy : typing.Optional[GatewayProfileUpdateIntegrationPolicy]
            Omit to leave unchanged; send {"mode": "all"} to allow all integrations

        internet_enabled : typing.Optional[bool]

        is_default : typing.Optional[bool]

        name : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[GatewayProfileResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"gateway/profiles/{encode_path_param(profile_id)}",
            base_url=self._client_wrapper.get_environment().control,
            method="PATCH",
            json={
                "cloud_role": cloud_role,
                "default_action": default_action,
                "description": description,
                "integration_policy": convert_and_respect_annotation_metadata(
                    object_=integration_policy,
                    annotation=typing.Optional[GatewayProfileUpdateIntegrationPolicy],
                    direction="write",
                ),
                "internet_enabled": internet_enabled,
                "is_default": is_default,
                "name": name,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GatewayProfileResponse,
                    parse_obj_as(
                        type_=GatewayProfileResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create_gateway_rule(
        self,
        profile_id: str,
        *,
        host_pattern: str,
        action: typing.Optional[GatewayAction] = OMIT,
        auth_strategy: typing.Optional[AuthStrategySchema] = OMIT,
        content_filter: typing.Optional[GatewayRuleCreateContentFilter] = OMIT,
        methods: typing.Optional[typing.Sequence[str]] = OMIT,
        path_pattern: typing.Optional[str] = OMIT,
        priority: typing.Optional[int] = OMIT,
        provider_key: typing.Optional[str] = OMIT,
        rate_limit_rpm: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[GatewayRuleResponse]:
        """
        Parameters
        ----------
        profile_id : str

        host_pattern : str

        action : typing.Optional[GatewayAction]

        auth_strategy : typing.Optional[AuthStrategySchema]

        content_filter : typing.Optional[GatewayRuleCreateContentFilter]

        methods : typing.Optional[typing.Sequence[str]]

        path_pattern : typing.Optional[str]

        priority : typing.Optional[int]

        provider_key : typing.Optional[str]

        rate_limit_rpm : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[GatewayRuleResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"gateway/profiles/{encode_path_param(profile_id)}/rules",
            base_url=self._client_wrapper.get_environment().control,
            method="POST",
            json={
                "action": action,
                "auth_strategy": convert_and_respect_annotation_metadata(
                    object_=auth_strategy, annotation=typing.Optional[AuthStrategySchema], direction="write"
                ),
                "content_filter": convert_and_respect_annotation_metadata(
                    object_=content_filter,
                    annotation=typing.Optional[GatewayRuleCreateContentFilter],
                    direction="write",
                ),
                "host_pattern": host_pattern,
                "methods": methods,
                "path_pattern": path_pattern,
                "priority": priority,
                "provider_key": provider_key,
                "rate_limit_rpm": rate_limit_rpm,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GatewayRuleResponse,
                    parse_obj_as(
                        type_=GatewayRuleResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def reorder_gateway_rules(
        self,
        profile_id: str,
        *,
        rules: typing.Sequence[RuleReorderItem],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[typing.List[GatewayRuleResponse]]:
        """
        Parameters
        ----------
        profile_id : str

        rules : typing.Sequence[RuleReorderItem]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.List[GatewayRuleResponse]]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"gateway/profiles/{encode_path_param(profile_id)}/rules/reorder",
            base_url=self._client_wrapper.get_environment().control,
            method="POST",
            json={
                "rules": convert_and_respect_annotation_metadata(
                    object_=rules, annotation=typing.Sequence[RuleReorderItem], direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[GatewayRuleResponse],
                    parse_obj_as(
                        type_=typing.List[GatewayRuleResponse],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def delete_gateway_rule(
        self, profile_id: str, rule_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[None]:
        """
        Parameters
        ----------
        profile_id : str

        rule_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[None]
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"gateway/profiles/{encode_path_param(profile_id)}/rules/{encode_path_param(rule_id)}",
            base_url=self._client_wrapper.get_environment().control,
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return AsyncHttpResponse(response=_response, data=None)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def update_gateway_rule(
        self,
        profile_id: str,
        rule_id: str,
        *,
        action: typing.Optional[GatewayAction] = OMIT,
        auth_strategy: typing.Optional[AuthStrategySchema] = OMIT,
        content_filter: typing.Optional[GatewayRuleUpdateContentFilter] = OMIT,
        host_pattern: typing.Optional[str] = OMIT,
        methods: typing.Optional[typing.Sequence[str]] = OMIT,
        path_pattern: typing.Optional[str] = OMIT,
        priority: typing.Optional[int] = OMIT,
        provider_key: typing.Optional[str] = OMIT,
        rate_limit_rpm: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[GatewayRuleResponse]:
        """
        Parameters
        ----------
        profile_id : str

        rule_id : str

        action : typing.Optional[GatewayAction]

        auth_strategy : typing.Optional[AuthStrategySchema]

        content_filter : typing.Optional[GatewayRuleUpdateContentFilter]

        host_pattern : typing.Optional[str]

        methods : typing.Optional[typing.Sequence[str]]

        path_pattern : typing.Optional[str]

        priority : typing.Optional[int]

        provider_key : typing.Optional[str]

        rate_limit_rpm : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[GatewayRuleResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"gateway/profiles/{encode_path_param(profile_id)}/rules/{encode_path_param(rule_id)}",
            base_url=self._client_wrapper.get_environment().control,
            method="PATCH",
            json={
                "action": action,
                "auth_strategy": convert_and_respect_annotation_metadata(
                    object_=auth_strategy, annotation=typing.Optional[AuthStrategySchema], direction="write"
                ),
                "content_filter": convert_and_respect_annotation_metadata(
                    object_=content_filter,
                    annotation=typing.Optional[GatewayRuleUpdateContentFilter],
                    direction="write",
                ),
                "host_pattern": host_pattern,
                "methods": methods,
                "path_pattern": path_pattern,
                "priority": priority,
                "provider_key": provider_key,
                "rate_limit_rpm": rate_limit_rpm,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GatewayRuleResponse,
                    parse_obj_as(
                        type_=GatewayRuleResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
