# This file was auto-generated by Fern from our API Definition.

import typing

from ...core import enum

T_Result = typing.TypeVar("T_Result")


class ListKnowledgeVersionsRequestSort(enum.StrEnum):
    VERSION_NUMBER = "-version_number"
    VERSION_NUMBER = "version_number"
    _UNKNOWN = "__LISTKNOWLEDGEVERSIONSREQUESTSORT_UNKNOWN__"
    """
    This member is used for forward compatibility. If the value is not recognized by the enum, it will be stored here, and the raw value is accessible through `.value`.
    """

    @classmethod
    def _missing_(cls, value: typing.Any) -> "ListKnowledgeVersionsRequestSort":
        unknown = cls._UNKNOWN
        unknown._value_ = value
        return unknown

    def visit(
        self, version_number: typing.Callable[[], T_Result], _unknown_member: typing.Callable[[str], T_Result]
    ) -> T_Result:
        if self is ListKnowledgeVersionsRequestSort.VERSION_NUMBER:
            return version_number()
        if self is ListKnowledgeVersionsRequestSort.VERSION_NUMBER:
            return version_number()
        return _unknown_member(self._value_)
