# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.idempotency_config import IdempotencyConfig
from ..types.incoming_webhook import IncomingWebhook
from ..types.incoming_webhook_auth import IncomingWebhookAuth
from ..types.incoming_webhook_rule import IncomingWebhookRule
from ..types.incoming_webhook_status import IncomingWebhookStatus
from ..types.incoming_webhook_target import IncomingWebhookTarget
from .raw_client import AsyncRawWebhooksClient, RawWebhooksClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class WebhooksClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawWebhooksClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawWebhooksClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawWebhooksClient
        """
        return self._raw_client

    def list_incoming_webhooks(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[IncomingWebhook]:
        """
        List active incoming webhooks for the tenant.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[IncomingWebhook]
            Incoming webhooks

        Examples
        --------
        from islo import Islo
        from islo.environment import IsloEnvironment

        client = Islo(
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )
        client.webhooks.list_incoming_webhooks()
        """
        _response = self._raw_client.list_incoming_webhooks(request_options=request_options)
        return _response.data

    def create_incoming_webhook(
        self,
        *,
        auth: IncomingWebhookAuth,
        idempotency: IdempotencyConfig,
        name: str,
        target: IncomingWebhookTarget,
        rules: typing.Optional[typing.Sequence[IncomingWebhookRule]] = OMIT,
        status: typing.Optional[IncomingWebhookStatus] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> IncomingWebhook:
        """
        Create a tenant-scoped incoming webhook receiver. The receiver URL accepts external webhook deliveries and routes them to a resolved sandbox.

        Parameters
        ----------
        auth : IncomingWebhookAuth

        idempotency : IdempotencyConfig

        name : str

        target : IncomingWebhookTarget

        rules : typing.Optional[typing.Sequence[IncomingWebhookRule]]

        status : typing.Optional[IncomingWebhookStatus]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        IncomingWebhook
            Incoming webhook created

        Examples
        --------
        from islo import (
            IdempotencyConfig_Header,
            IncomingWebhookAuthZero,
            IncomingWebhookTarget_FixedSandboxName,
            Islo,
        )
        from islo.environment import IsloEnvironment

        client = Islo(
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )
        client.webhooks.create_incoming_webhook(
            auth=IncomingWebhookAuthZero(
                auth_type="none",
            ),
            idempotency=IdempotencyConfig_Header(
                name="name",
            ),
            name="name",
            target=IncomingWebhookTarget_FixedSandboxName(
                sandbox_name="sandbox_name",
            ),
        )
        """
        _response = self._raw_client.create_incoming_webhook(
            auth=auth,
            idempotency=idempotency,
            name=name,
            target=target,
            rules=rules,
            status=status,
            request_options=request_options,
        )
        return _response.data

    def get_incoming_webhook(
        self, webhook_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> IncomingWebhook:
        """
        Get one incoming webhook by ID.

        Parameters
        ----------
        webhook_id : str
            Incoming webhook ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        IncomingWebhook
            Incoming webhook

        Examples
        --------
        from islo import Islo
        from islo.environment import IsloEnvironment

        client = Islo(
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )
        client.webhooks.get_incoming_webhook(
            webhook_id="webhook_id",
        )
        """
        _response = self._raw_client.get_incoming_webhook(webhook_id, request_options=request_options)
        return _response.data

    def delete_incoming_webhook(
        self, webhook_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Soft-delete an incoming webhook receiver.

        Parameters
        ----------
        webhook_id : str
            Incoming webhook ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from islo import Islo
        from islo.environment import IsloEnvironment

        client = Islo(
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )
        client.webhooks.delete_incoming_webhook(
            webhook_id="webhook_id",
        )
        """
        _response = self._raw_client.delete_incoming_webhook(webhook_id, request_options=request_options)
        return _response.data

    def update_incoming_webhook(
        self,
        webhook_id: str,
        *,
        auth: typing.Optional[IncomingWebhookAuth] = OMIT,
        idempotency: typing.Optional[IdempotencyConfig] = OMIT,
        name: typing.Optional[str] = OMIT,
        rules: typing.Optional[typing.Sequence[IncomingWebhookRule]] = OMIT,
        status: typing.Optional[IncomingWebhookStatus] = OMIT,
        target: typing.Optional[IncomingWebhookTarget] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> IncomingWebhook:
        """
        Partially update an incoming webhook receiver. Provided top-level fields replace the existing values.

        Parameters
        ----------
        webhook_id : str
            Incoming webhook ID

        auth : typing.Optional[IncomingWebhookAuth]

        idempotency : typing.Optional[IdempotencyConfig]

        name : typing.Optional[str]

        rules : typing.Optional[typing.Sequence[IncomingWebhookRule]]

        status : typing.Optional[IncomingWebhookStatus]

        target : typing.Optional[IncomingWebhookTarget]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        IncomingWebhook
            Updated incoming webhook

        Examples
        --------
        from islo import Islo
        from islo.environment import IsloEnvironment

        client = Islo(
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )
        client.webhooks.update_incoming_webhook(
            webhook_id="webhook_id",
        )
        """
        _response = self._raw_client.update_incoming_webhook(
            webhook_id,
            auth=auth,
            idempotency=idempotency,
            name=name,
            rules=rules,
            status=status,
            target=target,
            request_options=request_options,
        )
        return _response.data


class AsyncWebhooksClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawWebhooksClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawWebhooksClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawWebhooksClient
        """
        return self._raw_client

    async def list_incoming_webhooks(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[IncomingWebhook]:
        """
        List active incoming webhooks for the tenant.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[IncomingWebhook]
            Incoming webhooks

        Examples
        --------
        import asyncio

        from islo import AsyncIslo
        from islo.environment import IsloEnvironment

        client = AsyncIslo(
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )


        async def main() -> None:
            await client.webhooks.list_incoming_webhooks()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_incoming_webhooks(request_options=request_options)
        return _response.data

    async def create_incoming_webhook(
        self,
        *,
        auth: IncomingWebhookAuth,
        idempotency: IdempotencyConfig,
        name: str,
        target: IncomingWebhookTarget,
        rules: typing.Optional[typing.Sequence[IncomingWebhookRule]] = OMIT,
        status: typing.Optional[IncomingWebhookStatus] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> IncomingWebhook:
        """
        Create a tenant-scoped incoming webhook receiver. The receiver URL accepts external webhook deliveries and routes them to a resolved sandbox.

        Parameters
        ----------
        auth : IncomingWebhookAuth

        idempotency : IdempotencyConfig

        name : str

        target : IncomingWebhookTarget

        rules : typing.Optional[typing.Sequence[IncomingWebhookRule]]

        status : typing.Optional[IncomingWebhookStatus]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        IncomingWebhook
            Incoming webhook created

        Examples
        --------
        import asyncio

        from islo import (
            AsyncIslo,
            IdempotencyConfig_Header,
            IncomingWebhookAuthZero,
            IncomingWebhookTarget_FixedSandboxName,
        )
        from islo.environment import IsloEnvironment

        client = AsyncIslo(
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )


        async def main() -> None:
            await client.webhooks.create_incoming_webhook(
                auth=IncomingWebhookAuthZero(
                    auth_type="none",
                ),
                idempotency=IdempotencyConfig_Header(
                    name="name",
                ),
                name="name",
                target=IncomingWebhookTarget_FixedSandboxName(
                    sandbox_name="sandbox_name",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_incoming_webhook(
            auth=auth,
            idempotency=idempotency,
            name=name,
            target=target,
            rules=rules,
            status=status,
            request_options=request_options,
        )
        return _response.data

    async def get_incoming_webhook(
        self, webhook_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> IncomingWebhook:
        """
        Get one incoming webhook by ID.

        Parameters
        ----------
        webhook_id : str
            Incoming webhook ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        IncomingWebhook
            Incoming webhook

        Examples
        --------
        import asyncio

        from islo import AsyncIslo
        from islo.environment import IsloEnvironment

        client = AsyncIslo(
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )


        async def main() -> None:
            await client.webhooks.get_incoming_webhook(
                webhook_id="webhook_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_incoming_webhook(webhook_id, request_options=request_options)
        return _response.data

    async def delete_incoming_webhook(
        self, webhook_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Soft-delete an incoming webhook receiver.

        Parameters
        ----------
        webhook_id : str
            Incoming webhook ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from islo import AsyncIslo
        from islo.environment import IsloEnvironment

        client = AsyncIslo(
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )


        async def main() -> None:
            await client.webhooks.delete_incoming_webhook(
                webhook_id="webhook_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_incoming_webhook(webhook_id, request_options=request_options)
        return _response.data

    async def update_incoming_webhook(
        self,
        webhook_id: str,
        *,
        auth: typing.Optional[IncomingWebhookAuth] = OMIT,
        idempotency: typing.Optional[IdempotencyConfig] = OMIT,
        name: typing.Optional[str] = OMIT,
        rules: typing.Optional[typing.Sequence[IncomingWebhookRule]] = OMIT,
        status: typing.Optional[IncomingWebhookStatus] = OMIT,
        target: typing.Optional[IncomingWebhookTarget] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> IncomingWebhook:
        """
        Partially update an incoming webhook receiver. Provided top-level fields replace the existing values.

        Parameters
        ----------
        webhook_id : str
            Incoming webhook ID

        auth : typing.Optional[IncomingWebhookAuth]

        idempotency : typing.Optional[IdempotencyConfig]

        name : typing.Optional[str]

        rules : typing.Optional[typing.Sequence[IncomingWebhookRule]]

        status : typing.Optional[IncomingWebhookStatus]

        target : typing.Optional[IncomingWebhookTarget]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        IncomingWebhook
            Updated incoming webhook

        Examples
        --------
        import asyncio

        from islo import AsyncIslo
        from islo.environment import IsloEnvironment

        client = AsyncIslo(
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )


        async def main() -> None:
            await client.webhooks.update_incoming_webhook(
                webhook_id="webhook_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_incoming_webhook(
            webhook_id,
            auth=auth,
            idempotency=idempotency,
            name=name,
            rules=rules,
            status=status,
            target=target,
            request_options=request_options,
        )
        return _response.data
