# This file was auto-generated by Fern from our API Definition.

import typing

import httpx
from .base_client import AsyncBaseIslo, BaseIslo
from .core.logging import LogConfig, Logger


class Islo(BaseIslo):
    def __init__(
        self,
        *,
        base_url: str,
        public_tenant_id: typing.Optional[str] = None,
        public_user_id: typing.Optional[str] = None,
        token: typing.Optional[typing.Union[str, typing.Callable[[], str]]] = None,
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.Client] = None,
        logging: typing.Optional[typing.Union[LogConfig, Logger]] = None,
    ):
        super().__init__(
            base_url=base_url,
            public_tenant_id=public_tenant_id,
            public_user_id=public_user_id,
            token=token,
            headers=headers,
            timeout=timeout,
            follow_redirects=follow_redirects,
            httpx_client=httpx_client,
            logging=logging,
        )


class AsyncIslo(AsyncBaseIslo):
    def __init__(
        self,
        *,
        base_url: str,
        public_tenant_id: typing.Optional[str] = None,
        public_user_id: typing.Optional[str] = None,
        token: typing.Optional[typing.Union[str, typing.Callable[[], str]]] = None,
        headers: typing.Optional[typing.Dict[str, str]] = None,
        async_token: typing.Optional[typing.Callable[[], typing.Awaitable[str]]] = None,
        timeout: typing.Optional[float] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.AsyncClient] = None,
        logging: typing.Optional[typing.Union[LogConfig, Logger]] = None,
    ):
        super().__init__(
            base_url=base_url,
            public_tenant_id=public_tenant_id,
            public_user_id=public_user_id,
            token=token,
            headers=headers,
            async_token=async_token,
            timeout=timeout,
            follow_redirects=follow_redirects,
            httpx_client=httpx_client,
            logging=logging,
        )
