# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations


class IsloEnvironment:
    PRODUCTION: IsloEnvironment

    def __init__(self, *, control: str, compute: str):
        self.control = control
        self.compute = compute


IsloEnvironment.PRODUCTION = IsloEnvironment(control="https://api.islo.dev", compute="https://ca.compute.islo.dev")
