# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawSessionsClient, RawSessionsClient


class SessionsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSessionsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSessionsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSessionsClient
        """
        return self._raw_client

    def sandbox_attach_session(
        self, sandbox_name: str, session: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Parameters
        ----------
        sandbox_name : str
            Sandbox name

        session : str
            Session name

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from islo import Islo
        from islo.environment import IsloEnvironment

        client = Islo(
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )
        client.sessions.sandbox_attach_session(
            sandbox_name="sandbox_name",
            session="session",
        )
        """
        _response = self._raw_client.sandbox_attach_session(sandbox_name, session, request_options=request_options)
        return _response.data


class AsyncSessionsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSessionsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSessionsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSessionsClient
        """
        return self._raw_client

    async def sandbox_attach_session(
        self, sandbox_name: str, session: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Parameters
        ----------
        sandbox_name : str
            Sandbox name

        session : str
            Session name

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from islo import AsyncIslo
        from islo.environment import IsloEnvironment

        client = AsyncIslo(
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )


        async def main() -> None:
            await client.sessions.sandbox_attach_session(
                sandbox_name="sandbox_name",
                session="session",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.sandbox_attach_session(
            sandbox_name, session, request_options=request_options
        )
        return _response.data
