# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.create_session_response import CreateSessionResponse
from ..types.list_sessions_response import ListSessionsResponse
from .raw_client import AsyncRawSessionsClient, RawSessionsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class SessionsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSessionsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSessionsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSessionsClient
        """
        return self._raw_client

    def sandbox_list_sessions(
        self, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ListSessionsResponse:
        """
        Parameters
        ----------
        name : str
            Sandbox name

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListSessionsResponse
            Session list

        Examples
        --------
        from islo import Islo

        client = Islo(
            api_key="YOUR_API_KEY",
        )
        client.sessions.sandbox_list_sessions(
            name="name",
        )
        """
        _response = self._raw_client.sandbox_list_sessions(name, request_options=request_options)
        return _response.data

    def sandbox_create_session(
        self,
        name: str,
        *,
        create_session_request_name: str,
        command: typing.Optional[typing.Sequence[str]] = OMIT,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = OMIT,
        ttl: typing.Optional[str] = OMIT,
        user: typing.Optional[str] = OMIT,
        workdir: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateSessionResponse:
        """
        Parameters
        ----------
        name : str
            Sandbox name

        create_session_request_name : str

        command : typing.Optional[typing.Sequence[str]]

        env : typing.Optional[typing.Dict[str, typing.Optional[str]]]

        ttl : typing.Optional[str]

        user : typing.Optional[str]

        workdir : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateSessionResponse
            Session created

        Examples
        --------
        from islo import Islo

        client = Islo(
            api_key="YOUR_API_KEY",
        )
        client.sessions.sandbox_create_session(
            name="name",
            create_session_request_name="name",
        )
        """
        _response = self._raw_client.sandbox_create_session(
            name,
            create_session_request_name=create_session_request_name,
            command=command,
            env=env,
            ttl=ttl,
            user=user,
            workdir=workdir,
            request_options=request_options,
        )
        return _response.data

    def sandbox_kill_session(
        self, name: str, session: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Parameters
        ----------
        name : str
            Sandbox name

        session : str
            Session name

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from islo import Islo

        client = Islo(
            api_key="YOUR_API_KEY",
        )
        client.sessions.sandbox_kill_session(
            name="name",
            session="session",
        )
        """
        _response = self._raw_client.sandbox_kill_session(name, session, request_options=request_options)
        return _response.data

    def sandbox_attach_session(
        self, name: str, session: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Parameters
        ----------
        name : str
            Sandbox name

        session : str
            Session name

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from islo import Islo

        client = Islo(
            api_key="YOUR_API_KEY",
        )
        client.sessions.sandbox_attach_session(
            name="name",
            session="session",
        )
        """
        _response = self._raw_client.sandbox_attach_session(name, session, request_options=request_options)
        return _response.data


class AsyncSessionsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSessionsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSessionsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSessionsClient
        """
        return self._raw_client

    async def sandbox_list_sessions(
        self, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ListSessionsResponse:
        """
        Parameters
        ----------
        name : str
            Sandbox name

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListSessionsResponse
            Session list

        Examples
        --------
        import asyncio

        from islo import AsyncIslo

        client = AsyncIslo(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.sessions.sandbox_list_sessions(
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.sandbox_list_sessions(name, request_options=request_options)
        return _response.data

    async def sandbox_create_session(
        self,
        name: str,
        *,
        create_session_request_name: str,
        command: typing.Optional[typing.Sequence[str]] = OMIT,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = OMIT,
        ttl: typing.Optional[str] = OMIT,
        user: typing.Optional[str] = OMIT,
        workdir: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateSessionResponse:
        """
        Parameters
        ----------
        name : str
            Sandbox name

        create_session_request_name : str

        command : typing.Optional[typing.Sequence[str]]

        env : typing.Optional[typing.Dict[str, typing.Optional[str]]]

        ttl : typing.Optional[str]

        user : typing.Optional[str]

        workdir : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateSessionResponse
            Session created

        Examples
        --------
        import asyncio

        from islo import AsyncIslo

        client = AsyncIslo(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.sessions.sandbox_create_session(
                name="name",
                create_session_request_name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.sandbox_create_session(
            name,
            create_session_request_name=create_session_request_name,
            command=command,
            env=env,
            ttl=ttl,
            user=user,
            workdir=workdir,
            request_options=request_options,
        )
        return _response.data

    async def sandbox_kill_session(
        self, name: str, session: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Parameters
        ----------
        name : str
            Sandbox name

        session : str
            Session name

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from islo import AsyncIslo

        client = AsyncIslo(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.sessions.sandbox_kill_session(
                name="name",
                session="session",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.sandbox_kill_session(name, session, request_options=request_options)
        return _response.data

    async def sandbox_attach_session(
        self, name: str, session: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Parameters
        ----------
        name : str
            Sandbox name

        session : str
            Session name

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from islo import AsyncIslo

        client = AsyncIslo(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.sessions.sandbox_attach_session(
                name="name",
                session="session",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.sandbox_attach_session(name, session, request_options=request_options)
        return _response.data
