# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.job_list_item import JobListItem
from ..types.job_response import JobResponse
from ..types.job_run_response import JobRunResponse
from ..types.job_schedule_response import JobScheduleResponse
from ..types.job_version_response import JobVersionResponse
from .raw_client import AsyncRawJobsClient, RawJobsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class JobsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawJobsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawJobsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawJobsClient
        """
        return self._raw_client

    def validate_job_manifest(
        self,
        name: str,
        *,
        manifest: typing.Dict[str, typing.Any],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Parameters
        ----------
        name : str

        manifest : typing.Dict[str, typing.Any]
            Parsed job.toml content as JSON object

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from islo import Islo
        from islo.environment import IsloEnvironment

        client = Islo(
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )
        client.jobs.validate_job_manifest(
            name="name",
            manifest={"key": "value"},
        )
        """
        _response = self._raw_client.validate_job_manifest(name, manifest=manifest, request_options=request_options)
        return _response.data

    def deploy_job(
        self,
        name: str,
        *,
        manifest: typing.Dict[str, typing.Any],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> JobVersionResponse:
        """
        Parameters
        ----------
        name : str

        manifest : typing.Dict[str, typing.Any]
            Parsed job.toml content as JSON object

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        JobVersionResponse
            Successful Response

        Examples
        --------
        from islo import Islo
        from islo.environment import IsloEnvironment

        client = Islo(
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )
        client.jobs.deploy_job(
            name="name",
            manifest={"key": "value"},
        )
        """
        _response = self._raw_client.deploy_job(name, manifest=manifest, request_options=request_options)
        return _response.data

    def get_job(self, name: str, *, request_options: typing.Optional[RequestOptions] = None) -> JobResponse:
        """
        Parameters
        ----------
        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        JobResponse
            Successful Response

        Examples
        --------
        from islo import Islo
        from islo.environment import IsloEnvironment

        client = Islo(
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )
        client.jobs.get_job(
            name="name",
        )
        """
        _response = self._raw_client.get_job(name, request_options=request_options)
        return _response.data

    def list_jobs(
        self,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[JobListItem]:
        """
        Parameters
        ----------
        limit : typing.Optional[int]

        offset : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[JobListItem]
            Successful Response

        Examples
        --------
        from islo import Islo
        from islo.environment import IsloEnvironment

        client = Islo(
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )
        client.jobs.list_jobs()
        """
        _response = self._raw_client.list_jobs(limit=limit, offset=offset, request_options=request_options)
        return _response.data

    def list_job_versions(
        self,
        name: str,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[JobVersionResponse]:
        """
        Parameters
        ----------
        name : str

        limit : typing.Optional[int]

        offset : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[JobVersionResponse]
            Successful Response

        Examples
        --------
        from islo import Islo
        from islo.environment import IsloEnvironment

        client = Islo(
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )
        client.jobs.list_job_versions(
            name="name",
        )
        """
        _response = self._raw_client.list_job_versions(
            name, limit=limit, offset=offset, request_options=request_options
        )
        return _response.data

    def get_job_version(
        self, name: str, version_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> JobVersionResponse:
        """
        Parameters
        ----------
        name : str

        version_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        JobVersionResponse
            Successful Response

        Examples
        --------
        from islo import Islo
        from islo.environment import IsloEnvironment

        client = Islo(
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )
        client.jobs.get_job_version(
            name="name",
            version_id="version_id",
        )
        """
        _response = self._raw_client.get_job_version(name, version_id, request_options=request_options)
        return _response.data

    def list_job_runs(
        self,
        name: str,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[JobRunResponse]:
        """
        Parameters
        ----------
        name : str

        limit : typing.Optional[int]

        offset : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[JobRunResponse]
            Successful Response

        Examples
        --------
        from islo import Islo
        from islo.environment import IsloEnvironment

        client = Islo(
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )
        client.jobs.list_job_runs(
            name="name",
        )
        """
        _response = self._raw_client.list_job_runs(name, limit=limit, offset=offset, request_options=request_options)
        return _response.data

    def trigger_job_run(
        self,
        name: str,
        *,
        version_id: typing.Optional[str] = OMIT,
        region: typing.Optional[str] = OMIT,
        params: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> JobRunResponse:
        """
        Parameters
        ----------
        name : str

        version_id : typing.Optional[str]
            Deployed version to run; defaults to latest

        region : typing.Optional[str]
            Compute region override

        params : typing.Optional[typing.Dict[str, typing.Any]]
            Run-time parameter values (validated against [job.params])

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        JobRunResponse
            Successful Response

        Examples
        --------
        from islo import Islo
        from islo.environment import IsloEnvironment

        client = Islo(
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )
        client.jobs.trigger_job_run(
            name="name",
        )
        """
        _response = self._raw_client.trigger_job_run(
            name, version_id=version_id, region=region, params=params, request_options=request_options
        )
        return _response.data

    def get_job_run(
        self, name: str, run_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> JobRunResponse:
        """
        Parameters
        ----------
        name : str

        run_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        JobRunResponse
            Successful Response

        Examples
        --------
        from islo import Islo
        from islo.environment import IsloEnvironment

        client = Islo(
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )
        client.jobs.get_job_run(
            name="name",
            run_id="run_id",
        )
        """
        _response = self._raw_client.get_job_run(name, run_id, request_options=request_options)
        return _response.data

    def get_job_schedule(
        self, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> JobScheduleResponse:
        """
        Parameters
        ----------
        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        JobScheduleResponse
            Successful Response

        Examples
        --------
        from islo import Islo
        from islo.environment import IsloEnvironment

        client = Islo(
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )
        client.jobs.get_job_schedule(
            name="name",
        )
        """
        _response = self._raw_client.get_job_schedule(name, request_options=request_options)
        return _response.data

    def delete_job_schedule(self, name: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Parameters
        ----------
        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from islo import Islo
        from islo.environment import IsloEnvironment

        client = Islo(
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )
        client.jobs.delete_job_schedule(
            name="name",
        )
        """
        _response = self._raw_client.delete_job_schedule(name, request_options=request_options)
        return _response.data


class AsyncJobsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawJobsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawJobsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawJobsClient
        """
        return self._raw_client

    async def validate_job_manifest(
        self,
        name: str,
        *,
        manifest: typing.Dict[str, typing.Any],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Parameters
        ----------
        name : str

        manifest : typing.Dict[str, typing.Any]
            Parsed job.toml content as JSON object

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from islo import AsyncIslo
        from islo.environment import IsloEnvironment

        client = AsyncIslo(
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )


        async def main() -> None:
            await client.jobs.validate_job_manifest(
                name="name",
                manifest={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.validate_job_manifest(
            name, manifest=manifest, request_options=request_options
        )
        return _response.data

    async def deploy_job(
        self,
        name: str,
        *,
        manifest: typing.Dict[str, typing.Any],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> JobVersionResponse:
        """
        Parameters
        ----------
        name : str

        manifest : typing.Dict[str, typing.Any]
            Parsed job.toml content as JSON object

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        JobVersionResponse
            Successful Response

        Examples
        --------
        import asyncio

        from islo import AsyncIslo
        from islo.environment import IsloEnvironment

        client = AsyncIslo(
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )


        async def main() -> None:
            await client.jobs.deploy_job(
                name="name",
                manifest={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.deploy_job(name, manifest=manifest, request_options=request_options)
        return _response.data

    async def get_job(self, name: str, *, request_options: typing.Optional[RequestOptions] = None) -> JobResponse:
        """
        Parameters
        ----------
        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        JobResponse
            Successful Response

        Examples
        --------
        import asyncio

        from islo import AsyncIslo
        from islo.environment import IsloEnvironment

        client = AsyncIslo(
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )


        async def main() -> None:
            await client.jobs.get_job(
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_job(name, request_options=request_options)
        return _response.data

    async def list_jobs(
        self,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[JobListItem]:
        """
        Parameters
        ----------
        limit : typing.Optional[int]

        offset : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[JobListItem]
            Successful Response

        Examples
        --------
        import asyncio

        from islo import AsyncIslo
        from islo.environment import IsloEnvironment

        client = AsyncIslo(
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )


        async def main() -> None:
            await client.jobs.list_jobs()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_jobs(limit=limit, offset=offset, request_options=request_options)
        return _response.data

    async def list_job_versions(
        self,
        name: str,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[JobVersionResponse]:
        """
        Parameters
        ----------
        name : str

        limit : typing.Optional[int]

        offset : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[JobVersionResponse]
            Successful Response

        Examples
        --------
        import asyncio

        from islo import AsyncIslo
        from islo.environment import IsloEnvironment

        client = AsyncIslo(
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )


        async def main() -> None:
            await client.jobs.list_job_versions(
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_job_versions(
            name, limit=limit, offset=offset, request_options=request_options
        )
        return _response.data

    async def get_job_version(
        self, name: str, version_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> JobVersionResponse:
        """
        Parameters
        ----------
        name : str

        version_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        JobVersionResponse
            Successful Response

        Examples
        --------
        import asyncio

        from islo import AsyncIslo
        from islo.environment import IsloEnvironment

        client = AsyncIslo(
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )


        async def main() -> None:
            await client.jobs.get_job_version(
                name="name",
                version_id="version_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_job_version(name, version_id, request_options=request_options)
        return _response.data

    async def list_job_runs(
        self,
        name: str,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[JobRunResponse]:
        """
        Parameters
        ----------
        name : str

        limit : typing.Optional[int]

        offset : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[JobRunResponse]
            Successful Response

        Examples
        --------
        import asyncio

        from islo import AsyncIslo
        from islo.environment import IsloEnvironment

        client = AsyncIslo(
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )


        async def main() -> None:
            await client.jobs.list_job_runs(
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_job_runs(
            name, limit=limit, offset=offset, request_options=request_options
        )
        return _response.data

    async def trigger_job_run(
        self,
        name: str,
        *,
        version_id: typing.Optional[str] = OMIT,
        region: typing.Optional[str] = OMIT,
        params: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> JobRunResponse:
        """
        Parameters
        ----------
        name : str

        version_id : typing.Optional[str]
            Deployed version to run; defaults to latest

        region : typing.Optional[str]
            Compute region override

        params : typing.Optional[typing.Dict[str, typing.Any]]
            Run-time parameter values (validated against [job.params])

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        JobRunResponse
            Successful Response

        Examples
        --------
        import asyncio

        from islo import AsyncIslo
        from islo.environment import IsloEnvironment

        client = AsyncIslo(
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )


        async def main() -> None:
            await client.jobs.trigger_job_run(
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.trigger_job_run(
            name, version_id=version_id, region=region, params=params, request_options=request_options
        )
        return _response.data

    async def get_job_run(
        self, name: str, run_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> JobRunResponse:
        """
        Parameters
        ----------
        name : str

        run_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        JobRunResponse
            Successful Response

        Examples
        --------
        import asyncio

        from islo import AsyncIslo
        from islo.environment import IsloEnvironment

        client = AsyncIslo(
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )


        async def main() -> None:
            await client.jobs.get_job_run(
                name="name",
                run_id="run_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_job_run(name, run_id, request_options=request_options)
        return _response.data

    async def get_job_schedule(
        self, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> JobScheduleResponse:
        """
        Parameters
        ----------
        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        JobScheduleResponse
            Successful Response

        Examples
        --------
        import asyncio

        from islo import AsyncIslo
        from islo.environment import IsloEnvironment

        client = AsyncIslo(
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )


        async def main() -> None:
            await client.jobs.get_job_schedule(
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_job_schedule(name, request_options=request_options)
        return _response.data

    async def delete_job_schedule(self, name: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Parameters
        ----------
        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from islo import AsyncIslo
        from islo.environment import IsloEnvironment

        client = AsyncIslo(
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )


        async def main() -> None:
            await client.jobs.delete_job_schedule(
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_job_schedule(name, request_options=request_options)
        return _response.data
