# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.pagination import AsyncPager, SyncPager
from ..core.request_options import RequestOptions
from ..types.job_list_item import JobListItem
from ..types.job_manifest_input import JobManifestInput
from ..types.job_response import JobResponse
from ..types.job_run_list_item import JobRunListItem
from ..types.job_run_response import JobRunResponse
from ..types.job_schedule_response import JobScheduleResponse
from ..types.job_version_response import JobVersionResponse
from ..types.list_page_job_list_item import ListPageJobListItem
from ..types.list_page_job_run_list_item import ListPageJobRunListItem
from ..types.list_page_job_version_response import ListPageJobVersionResponse
from .raw_client import AsyncRawJobsClient, RawJobsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class JobsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawJobsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawJobsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawJobsClient
        """
        return self._raw_client

    def list_jobs(
        self,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[JobListItem, ListPageJobListItem]:
        """
        Parameters
        ----------
        limit : typing.Optional[int]

        cursor : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[JobListItem, ListPageJobListItem]
            Successful Response

        Examples
        --------
        from islo import Islo
        from islo.environment import IsloEnvironment

        client = Islo(
            "2026-09-15",
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )
        response = client.jobs.list_jobs()
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.list_jobs(limit=limit, cursor=cursor, request_options=request_options)

    def get_job(self, name: str, *, request_options: typing.Optional[RequestOptions] = None) -> JobResponse:
        """
        Parameters
        ----------
        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        JobResponse
            Successful Response

        Examples
        --------
        from islo import Islo
        from islo.environment import IsloEnvironment

        client = Islo(
            "2026-09-15",
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )
        client.jobs.get_job(
            name="name",
        )
        """
        _response = self._raw_client.get_job(name, request_options=request_options)
        return _response.data

    def delete_job(self, name: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Parameters
        ----------
        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from islo import Islo
        from islo.environment import IsloEnvironment

        client = Islo(
            "2026-09-15",
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )
        client.jobs.delete_job(
            name="name",
        )
        """
        _response = self._raw_client.delete_job(name, request_options=request_options)
        return _response.data

    def deploy_job(
        self, name: str, *, manifest: JobManifestInput, request_options: typing.Optional[RequestOptions] = None
    ) -> JobVersionResponse:
        """
        Parameters
        ----------
        name : str

        manifest : JobManifestInput
            Job manifest (authored as TOML or JSON, stored as JSON)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        JobVersionResponse
            Successful Response

        Examples
        --------
        from islo import (
            Islo,
            JobManifestInput,
            JobSection,
            RunSectionInput,
            TaskInput,
            TaskStepInput,
        )
        from islo.environment import IsloEnvironment

        client = Islo(
            "2026-09-15",
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )
        client.jobs.deploy_job(
            name="name",
            manifest=JobManifestInput(
                job=JobSection(
                    name="name",
                ),
                run=RunSectionInput(
                    tasks=[
                        TaskInput(
                            name="name",
                            steps=[TaskStepInput()],
                        )
                    ],
                ),
            ),
        )
        """
        _response = self._raw_client.deploy_job(name, manifest=manifest, request_options=request_options)
        return _response.data

    def list_job_runs(
        self,
        name: str,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[JobRunListItem, ListPageJobRunListItem]:
        """
        Parameters
        ----------
        name : str

        limit : typing.Optional[int]

        cursor : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[JobRunListItem, ListPageJobRunListItem]
            Successful Response

        Examples
        --------
        from islo import Islo
        from islo.environment import IsloEnvironment

        client = Islo(
            "2026-09-15",
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )
        response = client.jobs.list_job_runs(
            name="name",
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.list_job_runs(name, limit=limit, cursor=cursor, request_options=request_options)

    def trigger_job_run(
        self,
        name: str,
        *,
        params: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        region: typing.Optional[str] = OMIT,
        version_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> JobRunResponse:
        """
        Parameters
        ----------
        name : str

        params : typing.Optional[typing.Dict[str, typing.Any]]
            Run-time parameter values (validated against [job.params])

        region : typing.Optional[str]
            Compute region override

        version_id : typing.Optional[str]
            Deployed version to run; defaults to latest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        JobRunResponse
            Successful Response

        Examples
        --------
        from islo import Islo
        from islo.environment import IsloEnvironment

        client = Islo(
            "2026-09-15",
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )
        client.jobs.trigger_job_run(
            name="name",
        )
        """
        _response = self._raw_client.trigger_job_run(
            name, params=params, region=region, version_id=version_id, request_options=request_options
        )
        return _response.data

    def get_job_run(
        self, name: str, run_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> JobRunResponse:
        """
        Parameters
        ----------
        name : str

        run_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        JobRunResponse
            Successful Response

        Examples
        --------
        from islo import Islo
        from islo.environment import IsloEnvironment

        client = Islo(
            "2026-09-15",
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )
        client.jobs.get_job_run(
            name="name",
            run_id="run_id",
        )
        """
        _response = self._raw_client.get_job_run(name, run_id, request_options=request_options)
        return _response.data

    def stop_job_run(
        self,
        name: str,
        run_id: str,
        *,
        reason: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> JobRunResponse:
        """
        Parameters
        ----------
        name : str

        run_id : str

        reason : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        JobRunResponse
            Successful Response

        Examples
        --------
        from islo import Islo
        from islo.environment import IsloEnvironment

        client = Islo(
            "2026-09-15",
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )
        client.jobs.stop_job_run(
            name="name",
            run_id="run_id",
        )
        """
        _response = self._raw_client.stop_job_run(name, run_id, reason=reason, request_options=request_options)
        return _response.data

    def get_job_schedule(
        self, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> JobScheduleResponse:
        """
        Parameters
        ----------
        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        JobScheduleResponse
            Successful Response

        Examples
        --------
        from islo import Islo
        from islo.environment import IsloEnvironment

        client = Islo(
            "2026-09-15",
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )
        client.jobs.get_job_schedule(
            name="name",
        )
        """
        _response = self._raw_client.get_job_schedule(name, request_options=request_options)
        return _response.data

    def delete_job_schedule(self, name: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Parameters
        ----------
        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from islo import Islo
        from islo.environment import IsloEnvironment

        client = Islo(
            "2026-09-15",
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )
        client.jobs.delete_job_schedule(
            name="name",
        )
        """
        _response = self._raw_client.delete_job_schedule(name, request_options=request_options)
        return _response.data

    def validate_job_manifest(
        self, name: str, *, manifest: JobManifestInput, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Parameters
        ----------
        name : str

        manifest : JobManifestInput
            Job manifest (authored as TOML or JSON, stored as JSON)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from islo import (
            Islo,
            JobManifestInput,
            JobSection,
            RunSectionInput,
            TaskInput,
            TaskStepInput,
        )
        from islo.environment import IsloEnvironment

        client = Islo(
            "2026-09-15",
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )
        client.jobs.validate_job_manifest(
            name="name",
            manifest=JobManifestInput(
                job=JobSection(
                    name="name",
                ),
                run=RunSectionInput(
                    tasks=[
                        TaskInput(
                            name="name",
                            steps=[TaskStepInput()],
                        )
                    ],
                ),
            ),
        )
        """
        _response = self._raw_client.validate_job_manifest(name, manifest=manifest, request_options=request_options)
        return _response.data

    def list_job_versions(
        self,
        name: str,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[JobVersionResponse, ListPageJobVersionResponse]:
        """
        Parameters
        ----------
        name : str

        limit : typing.Optional[int]

        cursor : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[JobVersionResponse, ListPageJobVersionResponse]
            Successful Response

        Examples
        --------
        from islo import Islo
        from islo.environment import IsloEnvironment

        client = Islo(
            "2026-09-15",
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )
        response = client.jobs.list_job_versions(
            name="name",
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.list_job_versions(name, limit=limit, cursor=cursor, request_options=request_options)

    def get_job_version(
        self, name: str, version_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> JobVersionResponse:
        """
        Parameters
        ----------
        name : str

        version_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        JobVersionResponse
            Successful Response

        Examples
        --------
        from islo import Islo
        from islo.environment import IsloEnvironment

        client = Islo(
            "2026-09-15",
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )
        client.jobs.get_job_version(
            name="name",
            version_id="version_id",
        )
        """
        _response = self._raw_client.get_job_version(name, version_id, request_options=request_options)
        return _response.data


class AsyncJobsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawJobsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawJobsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawJobsClient
        """
        return self._raw_client

    async def list_jobs(
        self,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[JobListItem, ListPageJobListItem]:
        """
        Parameters
        ----------
        limit : typing.Optional[int]

        cursor : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[JobListItem, ListPageJobListItem]
            Successful Response

        Examples
        --------
        import asyncio

        from islo import AsyncIslo
        from islo.environment import IsloEnvironment

        client = AsyncIslo(
            "2026-09-15",
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )


        async def main() -> None:
            response = await client.jobs.list_jobs()
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.list_jobs(limit=limit, cursor=cursor, request_options=request_options)

    async def get_job(self, name: str, *, request_options: typing.Optional[RequestOptions] = None) -> JobResponse:
        """
        Parameters
        ----------
        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        JobResponse
            Successful Response

        Examples
        --------
        import asyncio

        from islo import AsyncIslo
        from islo.environment import IsloEnvironment

        client = AsyncIslo(
            "2026-09-15",
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )


        async def main() -> None:
            await client.jobs.get_job(
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_job(name, request_options=request_options)
        return _response.data

    async def delete_job(self, name: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Parameters
        ----------
        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from islo import AsyncIslo
        from islo.environment import IsloEnvironment

        client = AsyncIslo(
            "2026-09-15",
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )


        async def main() -> None:
            await client.jobs.delete_job(
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_job(name, request_options=request_options)
        return _response.data

    async def deploy_job(
        self, name: str, *, manifest: JobManifestInput, request_options: typing.Optional[RequestOptions] = None
    ) -> JobVersionResponse:
        """
        Parameters
        ----------
        name : str

        manifest : JobManifestInput
            Job manifest (authored as TOML or JSON, stored as JSON)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        JobVersionResponse
            Successful Response

        Examples
        --------
        import asyncio

        from islo import (
            AsyncIslo,
            JobManifestInput,
            JobSection,
            RunSectionInput,
            TaskInput,
            TaskStepInput,
        )
        from islo.environment import IsloEnvironment

        client = AsyncIslo(
            "2026-09-15",
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )


        async def main() -> None:
            await client.jobs.deploy_job(
                name="name",
                manifest=JobManifestInput(
                    job=JobSection(
                        name="name",
                    ),
                    run=RunSectionInput(
                        tasks=[
                            TaskInput(
                                name="name",
                                steps=[TaskStepInput()],
                            )
                        ],
                    ),
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.deploy_job(name, manifest=manifest, request_options=request_options)
        return _response.data

    async def list_job_runs(
        self,
        name: str,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[JobRunListItem, ListPageJobRunListItem]:
        """
        Parameters
        ----------
        name : str

        limit : typing.Optional[int]

        cursor : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[JobRunListItem, ListPageJobRunListItem]
            Successful Response

        Examples
        --------
        import asyncio

        from islo import AsyncIslo
        from islo.environment import IsloEnvironment

        client = AsyncIslo(
            "2026-09-15",
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )


        async def main() -> None:
            response = await client.jobs.list_job_runs(
                name="name",
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.list_job_runs(name, limit=limit, cursor=cursor, request_options=request_options)

    async def trigger_job_run(
        self,
        name: str,
        *,
        params: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        region: typing.Optional[str] = OMIT,
        version_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> JobRunResponse:
        """
        Parameters
        ----------
        name : str

        params : typing.Optional[typing.Dict[str, typing.Any]]
            Run-time parameter values (validated against [job.params])

        region : typing.Optional[str]
            Compute region override

        version_id : typing.Optional[str]
            Deployed version to run; defaults to latest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        JobRunResponse
            Successful Response

        Examples
        --------
        import asyncio

        from islo import AsyncIslo
        from islo.environment import IsloEnvironment

        client = AsyncIslo(
            "2026-09-15",
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )


        async def main() -> None:
            await client.jobs.trigger_job_run(
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.trigger_job_run(
            name, params=params, region=region, version_id=version_id, request_options=request_options
        )
        return _response.data

    async def get_job_run(
        self, name: str, run_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> JobRunResponse:
        """
        Parameters
        ----------
        name : str

        run_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        JobRunResponse
            Successful Response

        Examples
        --------
        import asyncio

        from islo import AsyncIslo
        from islo.environment import IsloEnvironment

        client = AsyncIslo(
            "2026-09-15",
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )


        async def main() -> None:
            await client.jobs.get_job_run(
                name="name",
                run_id="run_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_job_run(name, run_id, request_options=request_options)
        return _response.data

    async def stop_job_run(
        self,
        name: str,
        run_id: str,
        *,
        reason: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> JobRunResponse:
        """
        Parameters
        ----------
        name : str

        run_id : str

        reason : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        JobRunResponse
            Successful Response

        Examples
        --------
        import asyncio

        from islo import AsyncIslo
        from islo.environment import IsloEnvironment

        client = AsyncIslo(
            "2026-09-15",
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )


        async def main() -> None:
            await client.jobs.stop_job_run(
                name="name",
                run_id="run_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.stop_job_run(name, run_id, reason=reason, request_options=request_options)
        return _response.data

    async def get_job_schedule(
        self, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> JobScheduleResponse:
        """
        Parameters
        ----------
        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        JobScheduleResponse
            Successful Response

        Examples
        --------
        import asyncio

        from islo import AsyncIslo
        from islo.environment import IsloEnvironment

        client = AsyncIslo(
            "2026-09-15",
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )


        async def main() -> None:
            await client.jobs.get_job_schedule(
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_job_schedule(name, request_options=request_options)
        return _response.data

    async def delete_job_schedule(self, name: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Parameters
        ----------
        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from islo import AsyncIslo
        from islo.environment import IsloEnvironment

        client = AsyncIslo(
            "2026-09-15",
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )


        async def main() -> None:
            await client.jobs.delete_job_schedule(
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_job_schedule(name, request_options=request_options)
        return _response.data

    async def validate_job_manifest(
        self, name: str, *, manifest: JobManifestInput, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Parameters
        ----------
        name : str

        manifest : JobManifestInput
            Job manifest (authored as TOML or JSON, stored as JSON)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from islo import (
            AsyncIslo,
            JobManifestInput,
            JobSection,
            RunSectionInput,
            TaskInput,
            TaskStepInput,
        )
        from islo.environment import IsloEnvironment

        client = AsyncIslo(
            "2026-09-15",
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )


        async def main() -> None:
            await client.jobs.validate_job_manifest(
                name="name",
                manifest=JobManifestInput(
                    job=JobSection(
                        name="name",
                    ),
                    run=RunSectionInput(
                        tasks=[
                            TaskInput(
                                name="name",
                                steps=[TaskStepInput()],
                            )
                        ],
                    ),
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.validate_job_manifest(
            name, manifest=manifest, request_options=request_options
        )
        return _response.data

    async def list_job_versions(
        self,
        name: str,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[JobVersionResponse, ListPageJobVersionResponse]:
        """
        Parameters
        ----------
        name : str

        limit : typing.Optional[int]

        cursor : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[JobVersionResponse, ListPageJobVersionResponse]
            Successful Response

        Examples
        --------
        import asyncio

        from islo import AsyncIslo
        from islo.environment import IsloEnvironment

        client = AsyncIslo(
            "2026-09-15",
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )


        async def main() -> None:
            response = await client.jobs.list_job_versions(
                name="name",
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.list_job_versions(
            name, limit=limit, cursor=cursor, request_options=request_options
        )

    async def get_job_version(
        self, name: str, version_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> JobVersionResponse:
        """
        Parameters
        ----------
        name : str

        version_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        JobVersionResponse
            Successful Response

        Examples
        --------
        import asyncio

        from islo import AsyncIslo
        from islo.environment import IsloEnvironment

        client = AsyncIslo(
            "2026-09-15",
            api_key="YOUR_API_KEY",
            environment=IsloEnvironment.PRODUCTION,
        )


        async def main() -> None:
            await client.jobs.get_job_version(
                name="name",
                version_id="version_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_job_version(name, version_id, request_options=request_options)
        return _response.data
